PENALTY_FOR_SKIP = 100000000
PENALTY_FOR_EMPTY_ROUTE = PENALTY_FOR_SKIP * 2
PENALTY_FOR_ANOTHER_DRIVER_ORDER = PENALTY_FOR_SKIP * 3
PENALTY_FOR_WRONG_DEPOT = PENALTY_FOR_SKIP * 2
PENALTY_DRIVER_OVERTIME = 2000  # per second
TWO_DAYS = 2 * 24 * 60 * 60  # 48 hours

ORTOOLS_SEARCH_TIME_LIMIT = 20
ORTOOLS_SOLO_SEARCH_TIME_LIMIT = 4
