# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 08:33
from __future__ import unicode_literals

import base.utils
from django.db import migrations, models
import django.db.models.deletion

import radaro_utils.files.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routing', '0002_auto_20160203_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Company name...', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=radaro_utils.files.utils.get_upload_path)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routing.Location')),
            ],
        ),
    ]
