# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-04 12:10
from __future__ import unicode_literals

import base.utils
import django.core.validators
from django.db import migrations, models
import django.db.migrations.operations.special
import location_field.models.plain
import merchant.models.merchant
import timezone_field.fields


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# merchant.migrations.0009_auto_20160321_1119
# merchant.migrations.0016_auto_20160520_2132
# merchant.migrations.0020_auto_20160712_2010
import radaro_utils.files.utils



def default_sms_template():
    return "Hi, {{customer.name}}!\nGreat news, your order from {{merchant}} is on its way. " \
           "Click on the link to track your order in real-time. {{ url }}"


class Migration(migrations.Migration):

    replaces = [('merchant', '0001_initial'), ('merchant', '0002_auto_20160205_1034'), ('merchant', '0003_auto_20160208_1407'), ('merchant', '0004_remove_merchant_location'), ('merchant', '0005_auto_20160309_1350'), ('merchant', '0006_merchant_balance'), ('merchant', '0007_merchant_allow_geofence'), ('merchant', '0008_auto_20160321_1117'), ('merchant', '0009_auto_20160321_1119'), ('merchant', '0010_auto_20160321_1135'), ('merchant', '0011_merchant_allow_confirmation'), ('merchant', '0012_merchant_is_blocked'), ('merchant', '0013_auto_20160418_1130'), ('merchant', '0014_merchant_store_url'), ('merchant', '0015_merchant_country'), ('merchant', '0016_merchant_coloured_map'), ('merchant', '0016_auto_20160520_2132'), ('merchant', '0017_merge'), ('merchant', '0018_merchant_shorten_sms_url'), ('merchant', '0018_auto_20160705_0750'), ('merchant', '0019_merge'), ('merchant', '0020_auto_20160712_2010'), ('merchant', '0021_auto_20160802_0200'), ('merchant', '0022_auto_20160803_2136'), ('merchant', '0023_auto_20160805_1748'), ('merchant', '0024_merchant_hide_phones_of_drivers'), ('merchant', '0025_merchant_timezone'), ('merchant', '0026_auto_20161013_2102'), ('merchant', '0027_auto_20161018_0401'), ('merchant', '0028_merchant_geofence_upon_entering'), ('merchant', '0028_auto_20161102_0026'), ('merchant', '0029_merge_20161117_2137'), ('merchant', '0030_auto_20161117_2300'), ('merchant', '0031_auto_20161117_2301'), ('merchant', '0032_auto_20161117_2311'), ('merchant', '0033_auto_20161117_2327')]

    initial = True

    dependencies = [
        ('routing', '0002_auto_20160203_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=radaro_utils.files.utils.get_upload_path)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(default=None, max_length=63, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('allow_geofence', models.BooleanField(default=False)),
                ('abn', models.BigIntegerField(default=92116624001, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999999)])),
                ('distance_show_in', models.FloatField(choices=[(1609.344, 'Miles'), (1000, 'Kilometers')], default=1000)),
                ('phone', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='merchant',
            name='abn',
            field=models.BigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999999)]),
        ),
        migrations.AddField(
            model_name='merchant',
            name='allow_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchant',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, default=None, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='store_url',
            field=models.URLField(default='http://www.example.com/', verbose_name='Custom “URL” redirect link'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='country',
            field=models.CharField(choices=[('BY', 'Belarus'), ('AU', 'Australia')], default='AU', max_length=20),
        ),
        migrations.AddField(
            model_name='merchant',
            name='coloured_map',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='shorten_sms_url',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchant',
            name='sms_enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='sms_template',
            field=models.TextField(default=default_sms_template),
        ),
        migrations.AddField(
            model_name='merchant',
            name='sms_sender',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='abn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='job_price',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='merchant',
            name='sms_price',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='country',
            field=models.CharField(choices=[('BY', 'Belarus'), ('AU', 'Australia'), ('GB', 'United Kingdom'), ('US', 'USA')], default='AU', max_length=20),
        ),
        migrations.AddField(
            model_name='merchant',
            name='hide_phones_of_drivers',
            field=models.BooleanField(default=False, help_text="This function enables hiding driver's phones from customers."),
        ),
        migrations.AddField(
            model_name='merchant',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='Australia/Melbourne'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='date_format',
            field=models.CharField(choices=[('BE', 'ISO format (YYYY-MM-DD)'), ('LE', 'Europe format (DD/MM/YYYY)'), ('ME', 'USA format (MM/DD/YYYY)')], default='LE', help_text='This setting also affects processing incoming data. So there could be mistakes in processing dates of CSV file if user will suppose a date format, different from the one set here.', max_length=64),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='country',
            field=models.CharField(choices=[('BY', 'Belarus'), ('AU', 'Australia'), ('GB', 'United Kingdom'), ('US', 'USA'), ('AE', 'United Arab Emirates')], default='AU', max_length=20),
        ),
        migrations.AddField(
            model_name='merchant',
            name='geofence_upon_entering',
            field=models.BooleanField(default=True, help_text='If this option is checked, task will become completed after entering geo-fence area. Otherwise it will become completed after exiting geo-fence area. It has no effect if `allow geofence` option is disabled.'),
        ),
        migrations.AlterModelOptions(
            name='merchant',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='merchant',
            old_name='geofence_upon_entering',
            new_name='geofence_settings',
        ),
        migrations.AlterField(
            model_name='merchant',
            name='geofence_settings',
            field=models.IntegerField(choices=[(0, 'Disabled'), (1, 'Upon entering geofence area'), (2, 'Upon exiting geofence area')], default=0),
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='allow_geofence',
        ),
        migrations.AlterField(
            model_name='merchant',
            name='geofence_settings',
            field=models.IntegerField(choices=[(0, 'Disabled'), (1, 'Complete upon ENTER'), (2, 'Complete upon EXIT')], default=0),
        ),
    ]
