# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-28 09:24
from __future__ import unicode_literals

from django.db import migrations, models


def set_map_region(apps, schema_editor):
    BELARUS = 'BY'
    AUSTRALIA = 'AU'
    Merchant = apps.get_model('merchant', 'Merchant')
    Merchant.objects.filter(country=BELARUS).update(map_region='belarus')
    Merchant.objects.filter(country=AUSTRALIA).update(map_region='australia')


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0034_auto_20161123_1935_squashed_0056_merge_20170921_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='map_region',
            field=models.CharField(choices=[('belarus', 'Belarus'), ('australia', 'Australia'), ('us-south', 'US south'), ('us-west', 'US west'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.RunPython(set_map_region, migrations.RunPython.noop),
    ]
