# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-03 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0056_merchant_map_region'),
        ('merchant', '0057_auto_20170926_2335'),
    ]

    operations = [
    ]
