# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-05 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0058_merge_20171004_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='map_region',
            field=models.CharField(choices=[('belarus', 'Belarus'), ('australia', 'Australia'), ('us-south', 'US south'), ('us-west', 'US west'), ('other', 'Other')], default='other', help_text='This setting should be set if you want to enable `path processing` on map for merchant. This setting isn\'t available for all countries and regions. You may want to contact developers to add region or leave it as "OTHER" if you don\'t want to enable smooth car moving for merchant.', max_length=20),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='path_processing',
            field=models.BooleanField(default=False, help_text="Set this setting if you want to enable smooth car moving on map and processing GPS tracks after job completion for merchant. Please, notice that you should also set setting `map_region` but it can be unavailable for merchant's country. In such case, please, contact developers."),
        ),
    ]
