# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-28 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0058_merge_20171004_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='show_company_name_for_customer',
            field=models.BooleanField(default=True),
        ),
    ]
