# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-19 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0056_auto_20170927_1806_squashed_0058_auto_20171006_1720'),
        ('merchant', '0058_merge_20171004_0114'),
    ]

    operations = [
    ]
