# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-04 14:27
from __future__ import unicode_literals

from django.db import migrations, models


def update_altered_field(apps, schema_editor):
    Merchant = apps.get_model('merchant', 'Merchant')
    Merchant.objects.all().update(show_company_name_for_customer=False)


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0059_auto_20171229_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='show_company_name_for_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(update_altered_field, migrations.RunPython.noop)
    ]
