# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-08 12:37
from __future__ import unicode_literals

from django.db import migrations


def use_driver_phone_on_customer_page(apps, schema_editor):
    Merchant = apps.get_model('merchant', 'Merchant')
    Merchant.objects.filter(hide_phones_of_drivers=True).update(customer_tracking_phone_settings='driver')


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0060_auto_20171108_2337'),
    ]

    operations = [
        migrations.RunPython(code=use_driver_phone_on_customer_page, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField('Merchant', 'hide_phones_of_drivers'),
        migrations.RemoveField('Merchant', 'use_custom_phone_for_subbranding')
    ]
