# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-05 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0061_auto_20171108_2337'),
        ('merchant', '0059_auto_20180105_2129'),
        ('merchant', '0060_auto_20180105_0127'),
    ]

    operations = [
    ]
