# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-09 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0062_merge_20180105_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='customer_tracking_phone_settings',
            field=models.CharField(blank=True, choices=[('', 'Not display the phone number'), ('driver', 'Driver phone number'), ('merchant', 'Merchant phone number'), ('sub_branding', 'Sub-brand phone number')], default='', max_length=100),
        ),
    ]
