# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0065_auto_20180118_2221'),
        ('merchant', '0065_auto_20180307_2105'),
    ]

    operations = [
    ]
