# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 06:53
from __future__ import unicode_literals

from django.db import migrations


def move_country_to_countries(apps, schema_editor):
    Merchant = apps.get_model('merchant', 'Merchant')

    for m in Merchant.objects.all():
        m.countries = [m.country, ]
        m.save()


def move_countries_to_country(apps, schema_editor):
    Merchant = apps.get_model('merchant', 'Merchant')

    for m in Merchant.objects.all():
        m.country = m.countries[0]
        m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0067_auto_20180319_1753_part1'),
    ]

    operations = [
        migrations.RunPython(move_country_to_countries, move_countries_to_country),
    ]
