# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-10 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0072_merge_20180328_1719'),
        ('merchant', '0072_merge_20180323_2210'),
    ]

    operations = [
    ]
