# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 10:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


def migrate_prices(apps, schema_migration):
    Merchant = apps.get_model('merchant.Merchant')
    def_sms_cost = settings.CONSTANCE_CONFIG['DEFAULT_SMS_COST'][0]
    def_job_cost = settings.CONSTANCE_CONFIG['DEFAULT_JOB_COST'][0]
    Merchant.objects.filter(sms_price=0).update(sms_price=def_sms_cost)
    Merchant.objects.filter(job_price=0).update(job_price=def_job_cost)


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0066_events_to_sms_items_squashed_0075_merge_20180424_1821'),
    ]

    operations = [
        migrations.RunPython(code=migrate_prices, reverse_code=migrations.RunPython.noop)
    ]
