# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-14 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0073_merge_20180414_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='job_termination_sms_enable',
            field=models.BooleanField(default=True),
        ),
    ]
