# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0066_events_to_sms_items_squashed_0075_merge_20180424_1821'),
        ('merchant', '0074_auto_20180423_2034'),
    ]

    operations = [
    ]
