# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-27 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0076_merge_20180426_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='job_service_time',
            field=models.PositiveSmallIntegerField(choices=[(3, '3 Minutes'), (5, '5 Minutes'), (10, '10 Minutes'), (15, '15 Minutes'), (20, '20 Minutes'), (30, '30 Minutes'), (45, '45 Minutes'), (60, '1 Hour'), (90, '90 Minutes'), (120, '2 Hours')], default=5, help_text='Set average duration of time a driver needs to spend to on job site.This setting is useful only with "route optimization" enabled.'),
        ),
    ]
