# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0074_merchant_job_termination_sms_enable'),
        ('merchant', '0076_merge_20180426_1928'),
    ]

    operations = [
    ]
