# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-14 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0073_merge_20180410_2012'),
        ('merchant', '0077_merge_20180426_2334'),
    ]

    operations = [
    ]
