# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0078_merge_20180514_2314'),
        ('merchant', '0077_merchant_job_service_time'),
        ('merchant', '0066_merge_20180319_1717'),
    ]

    operations = [
    ]
