# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-23 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0078_merge_20180514_2314'),
        ('merchant', '0077_merchant_job_service_time'),
    ]

    operations = [
    ]
