# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0079_merge_20180516_0031'),
        ('merchant', '0079_merge_20180523_2141'),
    ]

    operations = [
    ]
