# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-12 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0079_merge_20180523_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='enable_clusterization',
            field=models.BooleanField(default=True, help_text="Disable this setting if you don't want to see clusters of pins on Radaro"),
        ),
    ]
