# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-15 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0079_merge_20180523_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='advanced_completion',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('optional', 'Optional'), ('required', 'Required')], default='disabled', max_length=50),
        ),
    ]
