# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-21 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0081_auto_20180615_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='high_resolution',
            field=models.BooleanField(default=False, verbose_name='Enable high resolution images'),
        ),
    ]
