# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-06 12:55
from __future__ import unicode_literals

from django.db import migrations

from notification.mixins import MessageTemplateStatus


def reverse_delete_migration(apps, schema_editor):
    TemplateSMSMessage = apps.get_model('notification', 'TemplateSMSMessage')
    MerchantSMSMessage = apps.get_model('merchant', 'MerchantSMSMessage')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    merchant_sms_types = [MessageTemplateStatus.INVITATION, MessageTemplateStatus.COMPLETE_INVITATION]

    for sms in TemplateSMSMessage.objects.filter(template__template_type__in=merchant_sms_types):
        merchant_sms = MerchantSMSMessage()
        merchant_sms.phone = sms.phone
        merchant_sms.message = sms.text
        merchant_sms.sender = sms.sender
        merchant_sms.segment_count = sms.segment_count
        merchant_sms.response_data = sms.response_data
        merchant_sms.price = sms.price
        merchant_sms.dispatched_at = sms.dispatched_at
        merchant_sms.sent_at = sms.sent_at
        merchant_sms.merchant = sms.template.merchant
        merchant_sms.polymorphic_ctype = ContentType.objects.get_for_model(MerchantSMSMessage, for_concrete_model=False)
        merchant_sms.save()


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0083_merge_20180627_2213'),
        ('notification', '0031_auto_20180530_2315')
    ]

    operations = [
        # migrations.RunPython(code=migrations.RunPython.noop, reverse_code=reverse_delete_migration),
        # migrations.RemoveField(
        #     model_name='merchantsmsmessage',
        #     name='merchant',
        # ),
        # migrations.DeleteModel(
        #     name='MerchantSMSMessage',
        # ),
    ]
