# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0083_merge_20180627_2213'),
        ('merchant', '0080_merge_20180611_1948'),
    ]

    operations = [
    ]
