# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-16 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0084_merchant_feedback_redirect_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='feedback_redirect_url',
        ),
        migrations.AddField(
            model_name='merchant',
            name='feedback_redirect_enabled',
            field=models.BooleanField(default=False, help_text='Redirect to custom URL without Radaro review'),
        ),
    ]
