# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-06 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0084_auto_20180706_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='first_reminder_sms_template',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='follow_up_reminder',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='follow_up_reminder_sms_template',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='job_termination_sms_enable',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='job_termination_sms_template',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='send_first_reminder',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='sms_template',
        ),
    ]
