# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-25 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0084_merge_20180704_2257'),
        ('merchant', '0080_auto_20180614_1834'),
    ]

    operations = [
    ]
