# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 14:11
from __future__ import unicode_literals

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0085_merchant_thumb_logo_100x100_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='thumb_logo_100x100_field',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=base.utils.ThumbnailsUploadPath()),
        ),
    ]
