# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 10:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0085_auto_20180706_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='delivery_interval',
            field=models.PositiveSmallIntegerField(default=3, help_text='Value (in hours) used for calculating "time_interval" in SMS/Email to Customer about upcoming delivery.', validators=[django.core.validators.MaxValueValidator(24)]),
        ),
    ]
