# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0085_merge_20180725_2251'),
        ('merchant', '0084_merchant_feedback_redirect_url'),
    ]

    operations = [
    ]
