# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-23 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0086_auto_20180817_0011'),
        ('merchant', '0085_auto_20180706_2259'),
    ]

    operations = [
    ]
