# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-21 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0086_auto_20180817_0011'),
        ('merchant', '0086_merge_20180815_2124'),
    ]

    operations = [
    ]
