# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-23 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0087_merge_20180823_2051'),
        ('merchant', '0086_auto_20180731_1848'),
    ]

    operations = [
    ]
