# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0088_merge_20180823_2114'),
        ('merchant', '0085_auto_20180816_1650'),
    ]

    operations = [
    ]
