# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-29 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0087_merge_20180822_0405'),
        ('merchant', '0089_merge_20180828_1933'),
    ]

    operations = [
    ]
