# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-07 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0086_merchant_delivery_interval'),
        ('merchant', '0089_merge_20180828_1933'),
    ]

    operations = [
    ]
