# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-30 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0089_merge_20180828_1933'),
        ('merchant', '0087_merge_20180827_2031'),
    ]

    operations = [
    ]
