# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0090_merge_20180830_1902'),
        ('merchant', '0090_merge_20180830_0017'),
    ]

    operations = [
    ]
