# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-03 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0090_merge_20180907_1932'),
        ('merchant', '0090_merchant_created_at'),
    ]

    operations = [
    ]
