# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-15 08:41
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models.functions import Substr


def migrate_sms_sender_name(apps, schema_editor):
    SubBranding = apps.get_model('merchant', 'SubBranding')
    SubBranding.objects.update(sms_sender=Substr('name', 1, 11))


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0091_merge_20181003_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='subbranding',
            name='sms_sender',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.RunPython(code=migrate_sms_sender_name, reverse_code=migrations.RunPython.noop)
    ]
