# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0090_merge_20180907_1932'),
        ('merchant', '0091_merge_20180830_2200'),
    ]

    operations = [
    ]
