# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-16 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0091_merge_20181003_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='driver_can_create_job',
            field=models.BooleanField(default=False, help_text='This setting allows drivers to create new jobs and assign them to other drivers.'),
        ),
    ]
