# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-30 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0092_subbranding_sms_sender'),
        ('merchant', '0092_merchant_driver_can_create_job'),
    ]

    operations = [
    ]
