# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-15 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0092_merge_20181006_0058'),
        ('merchant', '0091_merge_20181003_2240'),
    ]

    operations = [
    ]
