# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-21 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0093_merge_20181030_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='job_service_time',
            field=models.PositiveSmallIntegerField(choices=[(3, '3 Minutes'), (5, '5 Minutes'), (10, '10 Minutes'), (15, '15 Minutes'), (20, '20 Minutes'), (30, '30 Minutes'), (45, '45 Minutes'), (60, '1 Hour'), (90, '90 Minutes'), (120, '2 Hours')], default=5, help_text='Set average duration of time a driver needs to spend to on job site. This setting is useful only with "route optimisation" enabled.'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='route_optimization',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('ptv', 'PTV'), ('or-tools', "Google's OR Tools"), ('ptv_smartour_export', 'PTV Smartour export')], default='disabled', max_length=50, verbose_name='route optimisation'),
        ),
    ]
