# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-01 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0093_merge_20181030_2250'),
        ('merchant', '0094_merge_20181023_1834'),
    ]

    operations = [
    ]
