# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-30 11:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0095_merge_20181101_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='jobs_export_email',
            field=django.contrib.postgres.fields.citext.CIEmailField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subbranding',
            name='jobs_export_email',
            field=django.contrib.postgres.fields.citext.CIEmailField(blank=True, max_length=50),
        ),
    ]
