# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-29 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0094_auto_20181121_2232'),
        ('merchant', '0095_merge_20181101_1943'),
    ]

    operations = [
    ]
