# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-11 08:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0096_auto_20181130_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='pod_email',
            field=django.contrib.postgres.fields.citext.CIEmailField(blank=True, help_text='Email to send proof of delivery', max_length=50),
        ),
        migrations.AddField(
            model_name='subbranding',
            name='pod_email',
            field=django.contrib.postgres.fields.citext.CIEmailField(blank=True, help_text='Email to send proof of delivery', max_length=50),
        ),
    ]
