# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-10 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import merchant.models.merchant


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0097_auto_20181211_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='customer_review_screen_text',
            field=models.TextField(default=merchant.models.merchant.get_review_screen_default_text),
        ),
    ]
