# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-10 11:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_extension', '0004_auto_20190110_2200'),
        ('merchant', '0097_auto_20181211_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='sod_checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sod_merchants', to='merchant_extension.Checklist', verbose_name='Start-of-Day Checklist'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='sod_checklist_email',
            field=django.contrib.postgres.fields.citext.CIEmailField(blank=True, help_text='Use only with selected "sod_checklist" setting.', max_length=50, verbose_name='Start-of-Day Checklist Email'),
        ),
    ]
