# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-28 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0097_auto_20181211_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='in_app_jobs_assignment',
            field=models.BooleanField(default=False, help_text='Enable ability for drivers to see not assigned jobs and assign jobs on themselves from the app ', verbose_name='In-app jobs assignment'),
        ),
    ]
