# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-23 13:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchant', '0097_auto_20181211_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverHub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driverhub_driver', to=settings.AUTH_USER_MODEL)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driverhub_hub', to='merchant.Hub')),
            ],
        ),
        migrations.AddField(
            model_name='hub',
            name='drivers',
            field=models.ManyToManyField(related_name='wayback_hubs', through='merchant.DriverHub', to=settings.AUTH_USER_MODEL),
        ),
    ]
