# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-31 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0098_merchant_in_app_jobs_assignment'),
        ('merchant', '0098_merchant_review_screen_text'),
    ]

    operations = [
    ]
