# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-06 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0099_merge_20190131_2229'),
        ('merchant', '0099_auto_20190126_0039'),
    ]

    operations = [
    ]
