# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-05 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0099_merge_20190131_2229'),
        ('merchant', '0098_auto_20190110_2200'),
    ]

    operations = [
    ]
