# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0100_merge_20190206_0142'),
        ('merchant', '0100_merge_20190206_2214'),
    ]

    operations = [
    ]
