# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-13 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0100_merge_20190206_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.CharField(choices=[('red', 'Dark Red'), ('green', 'Dark Green'), ('blue', 'Turquoise'), ('yellow', 'Light Brown'), ('orange', 'Orange'), ('dark_blue', 'Dark Blue'), ('navy_blue', 'Navy Blue'), ('burgundy', 'Burgundy'), ('purple', 'Purple'), ('pink', 'Pink'), ('new_yellow', 'Yellow'), ('light_green', 'Light Green'), ('no_color', 'No color')], default='no_color', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together=set([('color', 'name', 'merchant')]),
        ),
    ]
