# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-27 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0101_merge_20190208_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='subbranding',
            name='reports_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('two_weeks', 'Every two weeks'), ('monthly', 'Monthly')], default='daily', max_length=100),
        ),
    ]
