# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0101_merge_20190208_1854'),
        ('merchant', '0096_merge_20181130_0745'),
    ]

    operations = [
    ]
