# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-06 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0102_subbranding_reports_frequency'),
        ('merchant', '0101_auto_20190214_0043'),
    ]

    operations = [
    ]
