# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0103_merge_20190306_2204'),
        ('merchant', '0102_merge_20190208_2030'),
    ]

    operations = [
    ]
