# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-04 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_extension', '0011_auto_20190320_2321'),
        ('merchant', '0103_merge_20190306_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='customer_survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchants', to='merchant_extension.Survey', verbose_name='Customer Survey'),
        ),
    ]
