# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-19 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0104_merge_20190402_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='signature_screen_text',
            field=models.TextField(blank=True, help_text='Proof of delivery signature', max_length=100),
        ),
    ]
