# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0104_merge_20190402_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='reports_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('two_weeks', 'Every two weeks'), ('monthly', 'Monthly')], default='daily', max_length=100),
        ),
        migrations.AddField(
            model_name='merchantgroup',
            name='core_merchant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchant.Merchant'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='merchant_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchants', to='merchant.MerchantGroup'),
        ),
    ]
