# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-21 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0105_merchant_signature_screen_text'),
        ('merchant', '0104_merchant_customer_survey'),
    ]

    operations = [
    ]
