# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-30 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0105_merchant_signature_screen_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('#8D87E3', 'Chetwode Blue'), ('#AE62D6', 'Lavender'), ('#22C2BD', 'Java'), ('#F56E8F', 'Froly'), ('#619F49', 'Fruit Salad'), ('#BE0649', 'Shiraz'), ('#FECE46', 'Bright Sun'), ('#B87437', 'Copper'), ('#891E28', 'Old Brick'), ('#4B4B4B', 'Tundora'), ('#FF7B1B', 'Pumpkin'), ('#E22B2B', 'Alizarin Crimson'), ('#6DB0CD', 'Danube'), ('#0C8F8A', 'Blue Chill'), ('#63BD6E', 'Fern'), ('#876C59', 'Beaver'), ('#A4BF35', 'Atlantis'), ('#5158F4', 'Royal Blue')], max_length=10)),
                ('is_secret', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='merchant',
            name='enable_skill_sets',
            field=models.BooleanField(default=False, verbose_name='Enable skill sets'),
        ),
        migrations.AddField(
            model_name='skillset',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.Merchant'),
        ),
        migrations.AlterUniqueTogether(
            name='skillset',
            unique_together=set([('name', 'color', 'merchant')]),
        ),
    ]
