# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-24 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0105_auto_20190416_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantgroup',
            name='webhook_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
