# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-09 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0106_merge_20190521_2122'),
        ('merchant', '0106_auto_20190531_0005'),
    ]

    operations = [
    ]
