# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-07 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0106_merge_20190521_2122'),
        ('merchant', '0106_auto_20190424_1908'),
    ]

    operations = [
    ]
