# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-08 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_extension', '0016_auto_20190617_2124'),
        ('merchant', '0106_merge_20190521_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='subbranding',
            name='customer_survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_brands', to='merchant_extension.Survey', verbose_name='Customer Survey'),
        ),
    ]
