# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-11 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0107_merge_20190607_2113'),
        ('merchant', '0107_merchant_customer_review_opt_in_enabled'),
    ]

    operations = [
    ]
