# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-13 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0108_merge_20190711_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='use_pick_up_status',
            field=models.BooleanField(default=False),
        ),
    ]
