# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-30 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0107_subbranding_customer_survey'),
        ('merchant', '0108_merge_20190711_1912'),
    ]

    operations = [
    ]
