# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-07 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0109_merge_20190730_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='enable_barcodes',
            field=models.BooleanField(default=False),
        ),
    ]
