# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-19 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0109_merge_20190730_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='pre_inspection_signature_screen_text',
            field=models.TextField(blank=True, help_text='Pre-inspection signature', max_length=100, verbose_name='Pre-inspection signature screen text'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='signature_screen_text',
            field=models.TextField(blank=True, help_text='Confirmation signature', max_length=100),
        ),
    ]
