# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-29 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0110_auto_20190819_1951'),
        ('merchant', '0107_merge_20190709_1542'),
    ]

    operations = [
    ]
