# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-30 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0111_merge_20190829_1747'),
        ('merchant', '0109_merchant_use_pick_up_status'),
    ]

    operations = [
    ]
