# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-03 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0111_merge_20190829_1747'),
        ('merchant', '0110_merchant_enable_barcodes'),
    ]

    operations = [
    ]
