# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-12 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0112_auto_20190906_1808'),
        ('merchant', '0112_merge_20190904_0000'),
        ('merchant', '0112_merge_20190830_1846'),
    ]

    operations = [
    ]
