# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-25 10:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0113_merge_20190912_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='driver_break_description',
            field=models.CharField(blank=True, max_length=150, verbose_name='"Take a break" dialogue description'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='driver_break_enabled',
            field=models.BooleanField(default=False, help_text="This option allows to inform drivers they can take a break", verbose_name='"Take a break" dialogue'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='driver_break_interval',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(24)], verbose_name='"Take a break" dialogue appearing interval', blank=True, null=True),
        ),
    ]
