# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-23 11:12
from __future__ import unicode_literals

from django.db import migrations, models

from merchant.models import Merchant


def fill_merchant_identifier(apps, schema_editor):
    MerchantModel = apps.get_model('merchant', 'Merchant')
    merchants = MerchantModel.objects.all()
    for merchant in merchants:
        merchant.merchant_identifier = Merchant.generate_identifier(merchant.name)
        merchant.save()


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0113_merge_20190912_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='merchant_identifier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RunPython(fill_merchant_identifier, migrations.RunPython.noop)
    ]
