# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-20 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0113_merge_20190912_1838'),
    ]

    operations = [
        # Set this field as True for existing merchants
        migrations.AddField(
            model_name='merchant',
            name='eta_with_traffic',
            field=models.BooleanField(default=True, verbose_name='ETA with traffic information'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='eta_with_traffic',
            field=models.BooleanField(default=False, verbose_name='ETA with traffic information'),
        ),
    ]
