# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-01 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0114_merchant_eta_with_traffic'),
        ('merchant', '0114_merchant_merchant_identifier'),
    ]

    operations = [
    ]
