# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-04 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0115_merge_20191001_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='job_failure_screen_text',
            field=models.TextField(blank=True, help_text='Sub-heading text for failed jobs on Customer tracking page', max_length=100, verbose_name='Customer tracking screen text at job failure'),
        ),
    ]
