# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-12-12 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0116_remove_merchant_driver_jobs_ordering'),
        ('merchant', '0114_auto_20190925_2001'),
        ('merchant', '0116_merchant_job_failure_screen_text'),
    ]

    operations = [
    ]
