# Generated by Django 2.2.5 on 2019-12-19 11:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations

import merchant.models.merchant


def fill_job_failure_screen_text_sub_heading(apps, schema_editor):
    Merchant = apps.get_model('merchant', 'Merchant')
    for merchant in Merchant.objects.all():
        merchant.job_failure_screen_text['sub_heading'] = merchant.job_failure_screen_text_old
        merchant.save(update_fields=['job_failure_screen_text'])


def fill_job_failure_screen_text(apps, schema_editor):
    Merchant = apps.get_model('merchant', 'Merchant')
    for merchant in Merchant.objects.all():
        merchant.job_failure_screen_text_old = merchant.job_failure_screen_text['sub_heading']
        merchant.save(update_fields=['job_failure_screen_text_old'])


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0117_merge_20191212_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='job_failure_screen_text',
            new_name='job_failure_screen_text_old',
        ),
        migrations.AddField(
            model_name='merchant',
            name='job_failure_screen_text',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=merchant.models.merchant.default_job_failure_screen_text_dict, help_text='Text for failed jobs on Customer tracking page', verbose_name='Customer tracking screen text at job failure'),
        ),
        migrations.RunPython(fill_job_failure_screen_text_sub_heading, reverse_code=fill_job_failure_screen_text),
    ]
