# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-11 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0117_auto_20191116_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='enable_barcodes',
        ),
    ]
