# Generated by Django 2.2.5 on 2019-12-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0118_auto_20191219_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='job_failure_screen_text_old',
        ),
    ]
