# Generated by Django 2.2.5 on 2020-01-10 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0119_remove_merchant_job_failure_screen_text_old'),
        ('merchant', '0118_remove_merchant_enable_barcodes'),
    ]

    operations = [
    ]
