# Generated by Django 2.2.5 on 2020-01-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0119_remove_merchant_job_failure_screen_text_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='round_corners_for_customer',
            field=models.BooleanField(default=False, help_text='Enable the rounding of the companies logos on customer tracking page', verbose_name='Rounding the logos on the tracking page'),
        ),
    ]
