# Generated by Django 2.2.5 on 2020-01-20 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0120_merchant_round_corners_for_customer'),
        ('merchant', '0120_merge_20200110_1758'),
    ]

    operations = [
    ]
