# Generated by Django 2.2.5 on 2020-02-04 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0120_merge_20200110_1758'),
        ('merchant', '0120_merchant_round_corners_for_customer'),
    ]

    operations = [
    ]
