# Generated by Django 2.2.5 on 2020-02-10 11:40
from constance import config
from django.db import migrations, models, transaction

from merchant.models.mixins import MerchantTypes


def fill_nti_merchant(apps, schema_editor):
    Merchant = apps.get_model('merchant', 'Merchant')
    sid = transaction.savepoint()
    try:
        with transaction.atomic():
            Merchant.objects.filter(id=config.NTI_MERCHANT_ID).update(merchant_type=MerchantTypes.MERCHANT_TYPES.NTI)
            transaction.savepoint_commit(sid)
    except:
        transaction.savepoint_rollback(sid)


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0120_merchant_round_corners_for_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='merchant_type',
            field=models.CharField(choices=[('DEFAULT', 'Default'), ('NTI', 'NTI'), ('MIELE_SURVEY', 'Miele Survey Merchant')], default='DEFAULT', max_length=15),
        ),
        migrations.RunPython(fill_nti_merchant, reverse_code=migrations.RunPython.noop),
    ]
