# Generated by Django 2.2.5 on 2020-02-14 10:57

import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0121_merchant_merchant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='survey_export_email',
            field=django.contrib.postgres.fields.citext.CIEmailField(blank=True, help_text='Email to send survey export', max_length=50),
        ),
        migrations.AddField(
            model_name='merchant',
            name='survey_reports_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('two_weeks', 'Every two weeks'), ('monthly', 'Monthly')], default='daily', max_length=15),
        ),
        migrations.AddField(
            model_name='subbranding',
            name='survey_export_email',
            field=django.contrib.postgres.fields.citext.CIEmailField(blank=True, help_text='Email to send survey export', max_length=50),
        ),
        migrations.AddField(
            model_name='subbranding',
            name='survey_reports_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('two_weeks', 'Every two weeks'), ('monthly', 'Monthly')], default='daily', max_length=15),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='reports_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('two_weeks', 'Every two weeks'), ('monthly', 'Monthly')], default='daily', max_length=15),
        ),
        migrations.AlterField(
            model_name='subbranding',
            name='reports_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('two_weeks', 'Every two weeks'), ('monthly', 'Monthly')], default='daily', max_length=15),
        ),
    ]
