# Generated by Django 2.2.5 on 2020-02-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0121_merge_20200121_0043'),
        ('merchant', '0121_merge_20200204_2234'),
    ]

    operations = [
    ]
