# Generated by Django 2.2.5 on 2020-03-03 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0122_auto_20200214_2157'),
        ('merchant', '0121_merge_20200204_2234'),
    ]

    operations = [
    ]
