# Generated by Django 2.2.5 on 2020-01-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0122_auto_20200214_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='enable_pick_up_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchant',
            name='pickup_signature_screen_text',
            field=models.TextField(blank=True, help_text='Pick-up confirmation signature', max_length=100),
        )
    ]
