# Generated by Django 2.2.5 on 2020-03-13 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0123_merge_20200304_0125'),
        ('merchant', '0123_auto_20200121_2002'),
    ]

    operations = [
    ]
