# Generated by Django 2.2.5 on 2020-03-03 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0122_merge_20200205_0116'),
        ('merchant', '0123_auto_20200121_2002'),
        ('merchant', '0123_auto_20200228_1803'),
    ]

    operations = [
    ]
