# Generated by Django 2.2.5 on 2020-05-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0124_merchant_shorten_report_url'),
        ('merchant', '0124_merchant_working_time'),
    ]

    operations = [
    ]
