# Generated by Django 2.2.5 on 2020-03-04 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0124_merge_20200303_1908'),
        ('merchant', '0123_merge_20200304_0125'),
    ]

    operations = [
    ]
