# Generated by Django 2.2.5 on 2020-04-09 10:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import merchant.models.merchant


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0124_merge_20200313_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='pickup_failure_screen_text',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=merchant.models.merchant.default_job_failure_screen_text_dict, help_text='Text for failed jobs on Pickup tracking page', verbose_name='Pickup tracking screen text at job failure'),
        ),
    ]
