# Generated by Django 2.2.5 on 2020-03-13 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0124_merge_20200313_2007'),
        ('merchant', '0125_merge_20200304_1839'),
    ]

    operations = [
    ]
