# Generated by Django 2.2.5 on 2020-05-28 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0125_merchant_pickup_failure_screen_text'),
        ('merchant', '0125_merge_20200506_2307'),
    ]

    operations = [
    ]
