# Generated by Django 2.2.5 on 2020-05-14 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0124_merge_20200326_2015'),
        ('merchant', '0125_merge_20200506_2307'),
    ]

    operations = [
    ]
