# Generated by Django 2.2.5 on 2020-05-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0125_merge_20200506_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='survey_export_directory',
            field=models.CharField(blank=True, verbose_name='Survey export SFTP directory', help_text="Path to merchant's survey results folder on SFTP server (e.g. 'delivery/survey_responses/...')", max_length=50),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='merchant_type',
            field=models.CharField(choices=[('DEFAULT', 'Default'), ('NTI', 'NTI'), ('MIELE_SURVEY', 'Miele Survey Merchant'), ('MIELE_DEFAULT', 'Miele Delivery/Service Merchant')], default='DEFAULT', max_length=15),
        ),
    ]
