# Generated by Django 2.2.5 on 2020-05-29 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0126_merge_20200514_1816'),
        ('merchant', '0126_auto_20200522_2155'),
    ]

    operations = [
    ]
