# Generated by Django 2.2.5 on 2020-03-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0126_merge_20200313_2329'),
        ('merchant', '0124_merge_20200326_2015'),
    ]

    operations = [
    ]
