# Generated by Django 2.2.5 on 2020-05-25 09:23

from django.db import migrations


def add_second_heading(apps, schema_migration):
    Merchant = apps.get_model('merchant.Merchant')
    for merchant in Merchant.objects.all():
        merchant.job_failure_screen_text['second_heading'] = ''
        merchant.assigned_job_screen_text['second_heading'] = ''
        merchant.not_assigned_job_screen_text['second_heading'] = ''
        merchant.save(
            update_fields=['job_failure_screen_text', 'assigned_job_screen_text', 'not_assigned_job_screen_text']
        )


def delete_second_heading(apps, schema_migration):
    Merchant = apps.get_model('merchant.Merchant')
    for merchant in Merchant.objects.all():
        merchant.job_failure_screen_text.pop('second_heading')
        merchant.assigned_job_screen_text.pop('second_heading')
        merchant.not_assigned_job_screen_text.pop('second_heading')
        merchant.save(
            update_fields=['job_failure_screen_text', 'assigned_job_screen_text', 'not_assigned_job_screen_text']
        )


class Migration(migrations.Migration):
    dependencies = [
        ('merchant', '0126_merge_20200514_1816'),
    ]

    operations = [
        migrations.RunPython(code=add_second_heading, reverse_code=delete_second_heading)
    ]
