# Generated by Django 2.2.5 on 2020-04-14 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0127_merge_20200326_2055'),
        ('merchant', '0124_merchant_shorten_report_url'),
    ]

    operations = [
    ]
