# Generated by Django 2.2.5 on 2020-06-04 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0127_merge_20200529_1934'),
        ('merchant', '0126_merge_20200528_2325'),
    ]

    operations = [
    ]
