# Generated by Django 2.2.5 on 2020-06-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0126_merchant_enable_delivery_confirmation_documents'),
        ('merchant', '0127_merge_20200529_1934'),
    ]

    operations = [
    ]
