# Generated by Django 2.2.5 on 2020-04-17 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0124_merchant_working_time'),
        ('merchant', '0128_merge_20200414_2046'),
    ]

    operations = [
    ]
