# Generated by Django 2.2.5 on 2020-04-24 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0129_merge_20200417_2029'),
        ('merchant', '0125_merchant_pickup_failure_screen_text'),
    ]

    operations = [
    ]
