# Generated by Django 2.2.5 on 2020-07-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0130_merge_20200622_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='forbid_drivers_unassign_jobs',
            field=models.BooleanField(default=False, verbose_name='Forbid drivers to unassign jobs from themselves'),
        ),
    ]
