# Generated by Django 2.2.5 on 2020-05-07 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0125_merge_20200506_2307'),
        ('merchant', '0130_merge_20200424_2148'),
    ]

    operations = [
    ]
