# Generated by Django 2.2.5 on 2020-07-22 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0131_merchant_forbid_driver_unassign_jobs'),
        ('merchant', '0131_merchant_enable_job_capacity'),
    ]

    operations = [
    ]
