# Generated by Django 2.2.5 on 2020-07-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0131_merchant_forbid_driver_unassign_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='enable_skids',
            field=models.BooleanField(default=False, verbose_name='Enable SKID adjustment'),
        ),
    ]
