# Generated by Django 2.2.5 on 2020-08-07 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0131_merchant_enable_job_capacity'),
        ('merchant', '0131_merchant_forbid_driver_unassign_jobs'),
    ]

    operations = [
    ]
