# Generated by Django 2.2.5 on 2020-05-14 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0126_merge_20200514_1816'),
        ('merchant', '0131_merge_20200507_2059'),
    ]

    operations = [
    ]
