# Generated by Django 2.2.5 on 2020-09-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0132_merge_20200808_0038'),
        ('merchant', '0132_merge_20200723_0005'),
    ]

    operations = [
    ]
