# Generated by Django 2.2.5 on 2020-05-20 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0132_merge_20200514_2101'),
        ('merchant', '0126_merchant_enable_delivery_confirmation_documents'),
    ]

    operations = [
    ]
