# Generated by Django 2.2.5 on 2020-09-18 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0133_auto_20200910_2231'),
        ('merchant', '0133_merge_20200906_0033'),
    ]

    operations = [
    ]
