# Generated by Django 2.2.5 on 2020-05-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0126_auto_20200522_2155'),
        ('merchant', '0133_merge_20200521_0704'),
    ]

    operations = [
    ]
