# Generated by Django 2.2.5 on 2020-10-13 08:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0133_auto_20200910_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='webhook_url',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), blank=True, default=list, size=5),
        ),
    ]
