# Generated by Django 2.2.5 on 2020-10-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0133_auto_20200910_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='scanned_document_output_size',
            field=models.CharField(choices=[('default', 'Default'), ('a4', 'A4'), ('us letter', 'US Letter')], default='default', max_length=20),
        ),
    ]
