# Generated by Django 2.2.5 on 2020-05-27 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0134_merge_20200527_0111'),
        ('merchant', '0127_auto_20200525_1923'),
    ]

    operations = [
    ]
