# Generated by Django 2.2.5 on 2020-10-14 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0134_merchant_scanned_document_output_size'),
        ('merchant', '0134_auto_20201013_1904'),
    ]

    operations = [
    ]
