# Generated by Django 2.2.5 on 2020-06-04 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0135_merge_20200527_1900'),
        ('merchant', '0127_merge_20200529_1934'),
    ]

    operations = [
    ]
