# Generated by Django 2.2.5 on 2020-10-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0136_auto_20201015_1858'),
        ('merchant', '0134_merge_20200918_1951'),
    ]

    operations = [
    ]
