# Generated by Django 2.2.5 on 2020-06-04 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0128_merge_20200604_2154'),
        ('merchant', '0136_merge_20200604_1921'),
    ]

    operations = [
    ]
