# Generated by Django 2.2.5 on 2021-01-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0137_merge_20201015_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillset',
            name='service_time',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
