# Generated by Django 2.2.5 on 2020-06-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0128_merge_20200608_2133'),
        ('merchant', '0137_merge_20200605_0132'),
    ]

    operations = [
    ]
