# Generated by Django 2.2.5 on 2021-01-26 11:40

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0137_merge_20201015_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='email_sender',
            field=django.contrib.postgres.fields.citext.CIEmailField(blank=True, help_text='The address for emails sender for all notifications to customers. If empty used the default "noreply@radaro.com.au" address.', max_length=50),
        ),
    ]
