# Generated by Django 2.2.5 on 2021-02-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0138_merchant_email_sender'),
        ('merchant', '0138_skillset_service_time'),
    ]

    operations = [
    ]
