# Generated by Django 2.2.5 on 2021-02-15 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0017_auto_20210215_2305'),
        ('merchant', '0139_merge_20210210_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='api_multi_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchants', to='webhooks.MerchantAPIKey'),
        ),
    ]
