# Generated by Django 2.2.5 on 2020-06-17 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0129_merchant_enable_reminder_to_attach_confirmation_documents'),
        ('merchant', '0138_merge_20200610_0110'),
    ]

    operations = [
    ]
