# Generated by Django 2.2.5 on 2020-07-06 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0139_merge_20200617_1732'),
        ('merchant', '0130_merge_20200622_2348'),
    ]

    operations = [
    ]
