# Generated by Django 2.2.5 on 2021-03-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0139_merge_20210210_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='email_sender_name',
            field=models.CharField(blank=True, help_text='The name for emails sender for all notifications to customers. If empty used the default "Radaro" name', max_length=50),
        ),
    ]
