# Generated by Django 2.2.5 on 2021-03-15 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0139_merchant_api_multi_key'),
        ('merchant', '0140_merchant_email_sender_name'),
    ]

    operations = [
    ]
