# Generated by Django 2.2.5 on 2020-07-17 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0131_merchant_forbid_driver_unassign_jobs'),
        ('merchant', '0140_merge_20200707_0049'),
    ]

    operations = [
    ]
