# Generated by Django 2.2.5 on 2021-03-15 12:38

from django.db import migrations
import merchant.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0141_merge_20210315_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='sms_sender',
            field=merchant.models.fields.SmsSenderField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='subbranding',
            name='sms_sender',
            field=merchant.models.fields.SmsSenderField(default='', max_length=15),
        ),
    ]
