# Generated by Django 2.2.5 on 2021-04-02 05:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0141_merge_20210315_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='subbranding',
            name='webhook_url',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), blank=True, default=list, size=5),
        ),
    ]
