# Generated by Django 2.2.5 on 2020-07-21 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0141_merge_20200717_2349'),
        ('merchant', '0131_merchant_enable_job_capacity'),
    ]

    operations = [
    ]
