# Generated by Django 2.2.5 on 2021-05-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0142_auto_20210315_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='enable_concatenated_orders',
            field=models.BooleanField(default=False),
        ),
    ]
