# Generated by Django 2.2.5 on 2020-08-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0142_merge_20200722_0157'),
        ('merchant', '0132_merchant_enable_skids'),
    ]

    operations = [
    ]
