# Generated by Django 2.2.5 on 2021-04-13 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0142_auto_20210315_2338'),
        ('merchant', '0142_merchant_pickup_service_time'),
    ]

    operations = [
    ]
