# Generated by Django 2.2.5 on 2021-04-15 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0142_subbranding_webhook_url'),
        ('merchant', '0142_auto_20210315_2338'),
    ]

    operations = [
    ]
