# Generated by Django 2.2.5 on 2021-05-05 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0143_merge_20210413_2247'),
        ('merchant', '0143_merge_20210415_1908'),
    ]

    operations = [
    ]
