# Generated by Django 2.2.5 on 2020-08-18 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0143_merge_20200806_0002'),
        ('merchant', '0132_merge_20200808_0038'),
    ]

    operations = [
    ]
