# Generated by Django 2.2.5 on 2021-05-19 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0144_merge_20210505_1713'),
        ('merchant', '0143_merchant_enable_concatenated_orders'),
    ]

    operations = [
    ]
