# Generated by Django 2.2.5 on 2021-07-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0144_merge_20210505_1713'),
        ('merchant', '0142_merchant_enable_saml_auth'),
    ]

    operations = [
    ]
