# Generated by Django 2.2.5 on 2020-10-09 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0134_merchant_scanned_document_output_size'),
        ('merchant', '0145_merge_20200914_2043'),
    ]

    operations = [
    ]
