# Generated by Django 2.2.5 on 2021-08-11 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0145_merge_20210713_2300'),
        ('merchant', '0145_merge_20210519_2151'),
    ]

    operations = [
    ]
