# Generated by Django 2.2.5 on 2021-10-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0146_merchant_time_today_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='notify_of_not_assigned_orders',
            field=models.BooleanField(default=False, verbose_name='Enable notification of available not assigned orders'),
        ),
    ]
