# Generated by Django 2.2.5 on 2020-10-13 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0134_auto_20201013_1904'),
        ('merchant', '0146_merge_20201009_2225'),
    ]

    operations = [
    ]
