# Generated by Django 2.2.5 on 2021-08-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0146_merge_20210714_0154'),
        ('merchant', '0146_merchant_time_today_reminder'),
    ]

    operations = [
    ]
