# Generated by Django 2.2.5 on 2020-10-15 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0147_merge_20201013_1939'),
        ('merchant', '0136_auto_20201015_1858'),
    ]

    operations = [
    ]
