# Generated by Django 2.2.5 on 2021-08-16 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0146_merge_20210811_1932'),
        ('merchant', '0147_merge_20210813_2132'),
    ]

    operations = [
    ]
