# Generated by Django 2.2.5 on 2021-08-23 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0147_merge_20210813_2132'),
        ('merchant', '0147_merge_20210810_2103'),
    ]

    operations = [
    ]
