# Generated by Django 2.2.5 on 2021-10-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0147_merge_20210813_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='enable_auto_complete_customer_fields',
            field=models.BooleanField(default=False, help_text='Drivers will get suggestions with customer details once they start typing customer phone or name', verbose_name='Auto-complete customer fields when driver creates job'),
        ),
    ]
