# Generated by Django 2.2.5 on 2021-09-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0147_merge_20210813_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='job_failure_signature_screen_text',
            field=models.TextField(blank=True, verbose_name='Fail job signature screen text', help_text='Job failure confirmation signature', max_length=100),
        ),
    ]
