# Generated by Django 2.2.5 on 2021-09-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0148_merchant_forbid_drivers_edit_schedule'),
        ('merchant', '0148_merchant_fail_job_signature_screen_text'),
    ]

    operations = [
    ]
