# Generated by Django 2.2.5 on 2021-09-01 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0148_merge_20210823_2048'),
        ('merchant', '0148_merge_20210816_1754'),
    ]

    operations = [
    ]
