# Generated by Django 2.2.5 on 2020-11-24 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0148_merge_20201015_1912'),
        ('merchant', '0137_merge_20201015_2217'),
    ]

    operations = [
    ]
