# Generated by Django 2.2.5 on 2021-10-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0149_merge_20210901_1737'),
        ('merchant', '0149_merge_20210927_2348'),
    ]

    operations = [
    ]
