# Generated by Django 2.2.5 on 2021-11-03 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0149_merge_20210927_2348'),
        ('merchant', '0148_merchant_enable_auto_complete_customer_fields'),
    ]

    operations = [
    ]
