# Generated by Django 2.2.5 on 2021-01-12 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0149_merge_20201124_2301'),
        ('merchant', '0138_skillset_service_time'),
    ]

    operations = [
    ]
