# Generated by Django 2.2.5 on 2021-01-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0150_merge_20210113_0154'),
        ('merchant', '0138_merchant_email_sender'),
    ]

    operations = [
    ]
