# Generated by Django 2.2.5 on 2021-11-18 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0147_merchant_notify_of_not_assigned_orders'),
        ('merchant', '0150_merge_20211014_2051'),
    ]

    operations = [
    ]
