# Generated by Django 2.2.5 on 2021-11-03 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0147_merchant_route_optimization_focus'),
        ('merchant', '0150_merge_20211014_2051'),
    ]

    operations = [
    ]
