# Generated by Django 2.2.5 on 2021-12-04 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0151_merge_20211103_2049'),
        ('merchant', '0151_merge_20211118_2348'),
    ]

    operations = [
    ]
