# Generated by Django 2.2.5 on 2021-02-15 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0151_merge_20210126_2354'),
        ('merchant', '0139_merge_20210210_0123'),
    ]

    operations = [
    ]
