# Generated by Django 2.2.5 on 2021-02-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0152_merge_20210215_2132'),
        ('merchant', '0139_merchant_api_multi_key'),
    ]

    operations = [
    ]
