# Generated by Django 2.2.5 on 2022-07-26 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('merchant_extension', '0021_auto_20220726_1706'),
        ('merchant', '0152_merge_20211205_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='eod_checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='eod_merchants', to='merchant_extension.Checklist',
                                    verbose_name='End-of-Day Checklist'),
        ),
    ]
