# Generated by Django 2.2.5 on 2022-07-26 10:38

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('merchant', '0153_merchant_eod_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='eod_checklist_email',
            field=django.contrib.postgres.fields.citext.CIEmailField(blank=True,
                                                                     help_text='Use only with selected "eod_checklist" setting.',
                                                                     max_length=50,
                                                                     verbose_name='End-of-Day Checklist Email'),
        ),
    ]
