# Generated by Django 2.2.5 on 2021-03-09 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0153_merge_20210228_0158'),
        ('merchant', '0140_merchant_email_sender_name'),
    ]

    operations = [
    ]
