# Generated by Django 2.2.5 on 2021-03-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0154_merge_20210310_0058'),
        ('merchant', '0142_auto_20210315_2338'),
    ]

    operations = [
    ]
