# Generated by Django 2.2.5 on 2021-04-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0155_merge_20210316_2244'),
        ('merchant', '0142_merchant_pickup_service_time'),
    ]

    operations = [
    ]
