# Generated by Django 2.2.5 on 2021-04-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0156_merge_20210406_2319'),
        ('merchant', '0142_subbranding_webhook_url'),
    ]

    operations = [
    ]
