# Generated by Django 2.2.5 on 2021-04-09 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0157_merge_20210408_0152'),
        ('merchant', '0142_merchant_enable_saml_auth'),
    ]

    operations = [
    ]
