# Generated by Django 2.2.5 on 2021-04-14 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0158_merge_20210409_2226'),
        ('merchant', '0143_merge_20210413_2247'),
    ]

    operations = [
    ]
