# Generated by Django 2.2.5 on 2021-04-30 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0159_merge_20210414_2205'),
        ('merchant', '0143_merge_20210415_1908'),
    ]

    operations = [
    ]
