# Generated by Django 2.2.5 on 2021-05-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0160_merge_20210430_2039'),
        ('merchant', '0144_merge_20210505_1713'),
    ]

    operations = [
    ]
