# Generated by Django 2.2.5 on 2021-05-31 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0145_merge_20210519_2151'),
        ('merchant', '0161_merge_20210507_2041'),
    ]

    operations = [
    ]
