# Generated by Django 2.2.5 on 2021-07-14 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0146_merge_20210714_0154'),
        ('merchant', '0162_merge_20210531_1750'),
    ]

    operations = [
    ]
