# Generated by Django 2.2.5 on 2021-07-30 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0163_merge_20210715_0304'),
        ('merchant', '0146_merchant_time_today_reminder'),
    ]

    operations = [
    ]
