# Generated by Django 2.2.5 on 2021-08-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0164_merge_20210731_0014'),
        ('merchant', '0146_merge_20210811_1932'),
    ]

    operations = [
    ]
