# Generated by Django 2.2.5 on 2021-08-16 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0165_merge_20210811_2007'),
        ('merchant', '0148_merge_20210816_1754'),
    ]

    operations = [
    ]
