# Generated by Django 2.2.5 on 2021-09-07 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0147_merchant_route_optimization_focus'),
        ('merchant', '0166_merge_20210816_1826'),
    ]

    operations = [
    ]
