# Generated by Django 2.2.5 on 2021-09-24 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0167_merge_20210907_1658'),
        ('merchant', '0148_merchant_forbid_drivers_edit_schedule'),
    ]

    operations = [
    ]
