# Generated by Django 2.2.5 on 2021-09-28 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0149_merge_20210927_2348'),
        ('merchant', '0168_merge_20210924_1729'),
    ]

    operations = [
    ]
