# Generated by Django 2.2.5 on 2021-11-01 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0169_merge_20210928_1707'),
        ('merchant', '0147_merchant_notify_of_not_assigned_orders'),
    ]

    operations = [
    ]
