# Generated by Django 2.2.5 on 2021-11-03 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0170_merge_20211101_2125'),
        ('merchant', '0150_merge_20211103_2201'),
    ]

    operations = [
    ]
