# Generated by Django 2.2.5 on 2021-11-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0150_merge_20211014_2051'),
        ('merchant', '0171_merge_20211103_2221'),
    ]

    operations = [
    ]
