# Generated by Django 2.2.5 on 2021-11-22 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0151_merge_20211118_2348'),
        ('merchant', '0172_merge_20211103_2333'),
    ]

    operations = [
    ]
