# Generated by Django 2.2.5 on 2021-12-06 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0173_merge_20211123_0226'),
        ('merchant', '0152_merge_20211205_0147'),
    ]

    operations = [
    ]
