# Generated by Django 2.2.5 on 2022-01-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0153_merchant_required_skill_sets_for_notify_orders'),
        ('merchant', '0174_merge_20211206_1535'),
    ]

    operations = [
    ]
