# Generated by Django 2.2.5 on 2022-06-23 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0175_merge_20220120_2023'),
        ('merchant', '0153_merchant_language'),
    ]

    operations = [
    ]
