# Generated by Django 2.2.5 on 2022-08-02 07:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('merchant', '0154_merchant_eod_checklist_email'),
        ('merchant', '0177_auto_20220712_2023'),
    ]

    operations = [
    ]
