# Generated by Django 2.2.5 on 2022-08-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0178_merge_20220802_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='confirmation_requirement',
            field=models.IntegerField(choices=[(0, 'Either signature required or photo required'), (1, 'Signature required and photo optional'), (2, 'Photo required and signature optional')], default=0),
        ),
        migrations.AddField(
            model_name='merchant',
            name='minimum_confirmation_photos',
            field=models.IntegerField(default=0),
        ),
    ]
