# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-02 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantapikey',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
