# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-07 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_merchantapikey_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantapikeyevents',
            name='user_agent',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
