# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-26 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0003_auto_20161007_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaljob',
            name='external_id',
            field=models.CharField(max_length=250),
        ),
    ]
