# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-16 13:22
from __future__ import unicode_literals

from django.db import migrations


def reverse_externaljob_delete_model(apps, schema_editor):
    ExternalJob = apps.get_model('tasks', 'ExternalJob')
    WebhooksExternalJob = apps.get_model('webhooks', 'ExternalJob')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    MerchantAPIKey = apps.get_model('webhooks', 'MerchantAPIKey')

    content_type = ContentType.objects.get_for_model(MerchantAPIKey)

    for job in ExternalJob.objects.filter(source_type=content_type):
        new_job = WebhooksExternalJob()
        new_job.external_id = job.external_id
        new_job.extra = job.extra
        new_job.api_key = MerchantAPIKey.objects.get(id=job.source_id)
        new_job.save()


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0004_auto_20161027_0040'),
        ('tasks', '0059_auto_20161116_2322'),
    ]

    operations = [
        migrations.RunPython(code=migrations.RunPython.noop, reverse_code=reverse_externaljob_delete_model),
        migrations.DeleteModel(name='externaljob'),
    ]
