# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 13:24
from __future__ import unicode_literals

from django.db import migrations


def set_authority(apps, schema_migration):
    MerchantAPIKey = apps.get_model('webhooks.MerchantAPIKey')
    Merchant = apps.get_model('merchant.Merchant')
    Member = apps.get_model('base.Member')
    MerchantAPIKeyEvents = apps.get_model('webhooks.MerchantAPIKeyEvents')

    for m_id in Merchant.objects.values_list('id', flat=True):
        managers = Member.managers.filter(merchant_id=m_id)
        _u = managers.order_by('role').last()
        api_keys = MerchantAPIKey.objects.filter(merchant_id=m_id)
        api_keys.update(creator=_u)
        MerchantAPIKeyEvents.objects.filter(merchant_api_key__in=api_keys).update(initiator=_u)


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0008_auto_20180426_2323'),
    ]

    operations = [
        migrations.RunPython(code=set_authority, reverse_code=migrations.RunPython.noop)
    ]
