# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 13:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0009_auto_20180426_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantapikey',
            name='merchant',
        ),
        migrations.AlterField(
            model_name='merchantapikey',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='merchantapikeyevents',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
