# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-17 08:05
from __future__ import unicode_literals

from django.db import migrations, connection


def fwd(apps, schena_migrations):
    with connection.cursor() as cursor:
        cursor.execute('UPDATE webhooks_merchantapikey k SET merchant_id = m.merchant_id '
                       'FROM base_member m WHERE k.creator_id = m.id')
        cursor.execute('UPDATE integrations_revelsystem r SET creator_id = '
                       '(SELECT m.id FROM base_member m '
                       'WHERE r.merchant_id = m.merchant_id '
                       'ORDER BY m.role DESC LIMIT 1)')
        cursor.execute('UPDATE tasks_bulkdelayedupload r SET creator_id = '
                       '(SELECT m.id FROM base_member m '
                       'WHERE r.merchant_id = m.merchant_id '
                       'ORDER BY m.role DESC LIMIT 1)')


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0112_auto_20180516_0033_1'),
        ('integrations', '0005_auto_20180717_0501_1'),
        ('webhooks', '0011_auto_20180717_0501_1'),
        ('base', '0058_auto_20180614_1834'),
    ]

    operations = [
        migrations.RunPython(code=fwd, reverse_code=migrations.RunPython.noop)
    ]
