# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-17 08:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0011_auto_20180717_0501_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantapikey',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='merchantapikey',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='merchant.Merchant'),
        ),
    ]
