# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-14 08:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0011_auto_20180717_0501_3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchantapikeyevents',
            options={'verbose_name_plural': 'Merchant api key events'},
        ),
        migrations.AddField(
            model_name='merchantapikeyevents',
            name='request_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantapikeyevents',
            name='request_method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='merchantapikeyevents',
            name='request_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='merchantapikeyevents',
            name='request_query_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantapikeyevents',
            name='response_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantapikeyevents',
            name='response_status',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
