# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-15 13:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0115_merge_20191001_2056'),
        ('webhooks', '0012_auto_20190314_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantWebhookEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_url', models.CharField(max_length=200)),
                ('request_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('elapsed_time', models.DurationField(blank=True, null=True)),
                ('exception_detail', models.TextField(blank=True, null=True)),
                ('happened_at', models.DateTimeField()),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.Merchant')),
            ],
            options={
                'ordering': ('-happened_at',),
            },
        ),
    ]
