# Generated by Django 2.2.5 on 2020-07-31 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0148_auto_20200630_2017'),
        ('webhooks', '0014_auto_20200318_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantwebhookevent',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Order'),
        ),
        migrations.AddField(
            model_name='merchantwebhookevent',
            name='topic',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
