# Generated by Django 2.2.5 on 2021-02-15 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0016_auto_20201015_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantAPIMultiKey',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('webhooks.merchantapikey',),
        ),
        migrations.AddField(
            model_name='merchantapikey',
            name='key_type',
            field=models.CharField(choices=[('single', 'Single-User'), ('multi', 'Multi-User')], default='single', max_length=10),
        ),
        migrations.AlterField(
            model_name='merchantapikey',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='merchant.Merchant'),
        ),
    ]
