# Generated by Django 2.2.5 on 2021-12-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0018_merchantwebhookevent_sub_branding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantapikeyevents',
            name='request_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
