# Generated by Django 2.2.5 on 2021-10-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0018_merchantwebhookevent_sub_branding'),
    ]

    operations = [
    ]
