# Generated by Django 2.2.5 on 2022-01-06 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0019_auto_20211029_2220'),
        ('webhooks', '0019_auto_20211229_2304'),
    ]

    operations = [
    ]
