# Generated by Django 2.2.5 on 2022-01-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0019_auto_20211029_2220'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='merchantwebhookevent',
            index=models.Index(fields=['-happened_at', '-id'], name='webhooks_me_happene_b788bb_idx'),
        ),
    ]
