# Generated by Django 2.2.5 on 2022-02-01 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0020_auto_20220124_2153'),
        ('webhooks', '0019_auto_20211229_2304'),
    ]

    operations = [
    ]
