# Generated by Django 2.2.5 on 2022-01-24 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0020_merge_20220106_1812'),
        ('webhooks', '0020_auto_20220124_2153'),
    ]

    operations = [
    ]
