# Generated by Django 2.2.5 on 2022-02-04 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0021_merge_20220201_2114'),
        ('webhooks', '0021_merge_20220124_2201'),
    ]

    operations = [
    ]
