# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-08 07:13
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant', '0059_auto_20171117_2107'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0101_auto_20170920_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driving_time', models.PositiveIntegerField()),
                ('driving_distance', models.PositiveIntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RouteOptimization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('failed', 'Failed'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='in_progress', max_length=25)),
                ('log', jsonfield.fields.JSONField(default=[])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.DateField(default=datetime.date.today)),
                ('tool', models.CharField(choices=[('ptv', 'PTV'), ('or-tools', "Google's OR Tools")], max_length=10)),
                ('input_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('drivers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_optimizations', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchant.Merchant')),
                ('skipped_orders', models.ManyToManyField(to='tasks.Order')),
            ],
            options={
                'ordering': ('-id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('point_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('point_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_points', to='routing_optimization.DriverRoute')),
            ],
        ),
        migrations.AddField(
            model_name='driverroute',
            name='optimization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_routes', to='routing_optimization.RouteOptimization'),
        ),
    ]
