# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-02 12:25
from __future__ import unicode_literals

from datetime import datetime

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def start_time_default():
    return datetime.min.time()


def end_time_default():
    return datetime.max.time()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchant', '0064_merge_20180222_2009'),
        ('routing_optimization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routeoptimization',
            name='drivers',
        ),
        migrations.AddField(
            model_name='driverroute',
            name='end_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ending_at', to='merchant.Hub'),
        ),
        migrations.AddField(
            model_name='driverroute',
            name='end_time',
            field=models.TimeField(default=end_time_default),
        ),
        migrations.AddField(
            model_name='driverroute',
            name='start_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='starting_at', to='merchant.Hub'),
        ),
        migrations.AddField(
            model_name='driverroute',
            name='start_time',
            field=models.TimeField(default=start_time_default),
        ),
        migrations.AlterField(
            model_name='driverroute',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_routes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='driverroute',
            name='driving_distance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverroute',
            name='driving_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='driverroute',
            unique_together=set([('optimization', 'driver')]),
        ),
        migrations.AlterField(
            model_name='routeoptimization',
            name='tool',
            field=models.CharField(choices=[('ptv', 'PTV'), ('or-tools', "Google's OR Tools"),
                                            ('ptv_smartour_export', 'PTV Smartour export')], max_length=50),
        ),
    ]
