# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing_optimization', '0002_auto_20180302_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeoptimization',
            name='day',
            field=models.DateField(),
        ),
    ]
