# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 08:27
from __future__ import unicode_literals

from django.db import migrations, models


def fill_fail_reason_field(apps, schema):
    RouteOptimization = apps.get_model('routing_optimization', 'routeoptimization')
    RouteOptimization.objects.filter(status='failed').update(fail_reason='Unknown error')


class Migration(migrations.Migration):

    dependencies = [
        ('routing_optimization', '0003_auto_20180403_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeoptimization',
            name='fail_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(fill_fail_reason_field, migrations.RunPython.noop),
    ]
