# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-02 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routing_optimization', '0004_routeoptimization_fail_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverroute',
            name='end_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ending_at', to='merchant.Hub'),
        ),
        migrations.AlterField(
            model_name='driverroute',
            name='start_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starting_at', to='merchant.Hub'),
        ),
    ]
