# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-12 15:06
from __future__ import unicode_literals


import datetime

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('routing_optimization', '0006_auto_20180613_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeoptimization',
            name='day',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.RemoveField(
            model_name='routeoptimization',
            name='day'
        ),
        migrations.AlterField(
            model_name='routeoptimization',
            name='fail_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),

        migrations.CreateModel(
            name='DriverRouteLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(default=None, max_length=63)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='driverroute',
            name='end_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='ending_at', to='routing_optimization.DriverRouteLocation'),
        ),
        migrations.AddField(
            model_name='driverroute',
            name='start_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='starting_at', to='routing_optimization.DriverRouteLocation'),
        ),
    ]
