# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-09 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing_optimization', '0007_auto_20180613_0106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routeoptimization',
            old_name='manager',
            new_name='created_by',
        ),
    ]
