# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-16 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routing_optimization', '0008_auto_20180709_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeoptimization',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='routeoptimization',
            name='parent_optimization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='child_optimizations', to='routing_optimization.RouteOptimization'),
        ),
    ]
