# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-21 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routing_optimization', '0009_auto_20180717_0154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routeoptimization',
            options={'ordering': ('-id',), 'verbose_name': 'Route Optimisation'},
        ),
        migrations.AlterField(
            model_name='driverroute',
            name='optimization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_routes', to='routing_optimization.RouteOptimization', verbose_name='optimisation'),
        ),
        migrations.AlterField(
            model_name='routeoptimization',
            name='parent_optimization',
            field=models.ForeignKey(default=None, null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_optimizations', to='routing_optimization.RouteOptimization', verbose_name='parent optimisation'),
        ),
    ]
