# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-10 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing_optimization', '0009_auto_20180717_0154'),
        ('routing_optimization', '0006_auto_20180713_0057'),
    ]

    operations = [
    ]
