# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-29 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing_optimization', '0010_auto_20181121_2232'),
        ('routing_optimization', '0010_merge_20180810_1743'),
    ]

    operations = [
    ]
