# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing_optimization', '0011_merge_20181130_0746'),
        ('routing_optimization', '0011_auto_20190122_2306'),
    ]

    operations = [
    ]
