# Generated by Django 2.2.5 on 2020-06-26 16:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing_optimization', '0012_merge_20190402_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeoptimization',
            name='google_api_requests',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
