# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-25 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlocation',
            name='accuracy',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='speed',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
