# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_auto_20161214_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlocation',
            name='point_type',
            field=models.IntegerField(choices=[(0, 'GPS'), (1, 'Real')], default=0),
        ),
    ]
