# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-23 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_driverlocation_point_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverlocation',
            options={'ordering': ('created_at',)},
        ),
        migrations.RenameField(
            model_name='driverlocation',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
