# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-23 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_auto_20170324_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlocation',
            name='bearing',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='timestamp',
            field=models.IntegerField(default=0),
        ),
    ]
