# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-04 15:23
from __future__ import unicode_literals

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):
    def migrate_old_style_locations(apps, scheme_editor):
        MATCHED = 1
        GPS_TRACK = 0
        DriverLocation = apps.get_model('driver', 'DriverLocation')
        for dl_matched in DriverLocation.objects.filter(point_type=MATCHED):
            loc = DriverLocation.objects\
                .filter(created_at__lt=dl_matched.created_at, point_type=GPS_TRACK).\
                order_by('created_at').last()
            loc.improved_location = dl_matched.location
            loc.save()

    dependencies = [
        ('driver', '0006_auto_20170324_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlocation',
            name='improved_location',
            field=location_field.models.plain.PlainLocationField(default=None, max_length=63, null=True, blank=True),
        ),
        migrations.RunPython(code=migrate_old_style_locations, reverse_code=migrations.RunPython.noop)
    ]
