# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0008_remove_driverlocation_point_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlocation',
            name='source',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
