# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-13 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0011_auto_20170713_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverlocation',
            name='timestamp',
        ),
        migrations.RenameField(
            model_name='driverlocation',
            old_name='temp_timestamp',
            new_name='timestamp',
        ),
    ]
