# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-23 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0012_remove_temp_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlocation',
            name='google_request_cost',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='google_requests',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='in_progress_orders',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
