class EventType:
    OBJECT_NOT_FOUND = 'not_found_on_validation'
    VALIDATION_ERROR = 'validation_error'
    DRIVER_TIME = 'driver_time'
    SIMPLE_MESSAGE = 'simple'
    RO_STATE_CHANGE = 'state_changed'
    ROUTE_STATE_CHANGE = 'route_state_changed'
    JOB_FILTERED = 'job_filtered'
    JOB_ADDED = 'job_added'
    DRIVER_NOT_AVAILABLE = 'driver_not_available'
    DELETE_RO = 'delete_optimisation'
    NOTIFY_CUSTOMERS = 'notify_customers'
    EXCEPTION = 'exception'
    EXCEPTION_ON_DELETION = 'exception_on_deletion'
    SKIPPED_OBJECTS = 'skipped_objects'
    ASSIGNED_AFTER_RO = 'assigned_jobs'
    CONTEXT_BUILDING = 'context_building'
    OPTIMISATION_PROCESS = 'optimisation_process'
    PROGRESS = 'progress'
    OLD_RO = 'old_ro'
    REMOVE_ROUTE_POINT = 'remove_point'
    REORDER_SEQUENCE = 'reorder_sequence'
    MOVE_JOBS = 'move_jobs'
    CREATE_RO_AFTER_MOVE_JOBS = 'create_ro_move_jobs'
    TRACK_API_STAT = 'track_api_stat'
    REFRESH_STATE_CHANGE = 'refresh_state_change'
    REFRESH_OPTIONS = 'refresh_options'
    FILL_POLYLINES = 'fill_polylines'
    TERMINATE_RO = 'terminate_optimisation'


class EventLabel:
    DEV = 'dev'
    ERROR = 'error'
    WARN = 'warn'
