# Generated by Django 2.2.5 on 2020-09-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_optimisation', '0002_remove_routeoptimisation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeoptimisation',
            name='customers_notified',
            field=models.BooleanField(default=False),
        ),
    ]
