# Generated by Django 2.2.5 on 2020-09-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_optimisation', '0003_routeoptimisation_customers_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverroute',
            name='state',
            field=models.CharField(choices=[('CREATED', 'Created'), ('RUNNING', 'Running'), ('FINISHED', 'Finished'), ('FAILED', 'Failed')], default='CREATED', max_length=12),
        ),
    ]
