# Generated by Django 2.2.5 on 2021-03-24 15:36

from django.db import migrations, models

from ..models import RoutePoint as RoutePointModel


def set_field_value(apps, schema):
    Order = apps.get_model('tasks', 'Order')
    Hub = apps.get_model('merchant', 'Hub')
    DriverRouteLocation = apps.get_model('route_optimisation', 'DriverRouteLocation')
    RoutePoint = apps.get_model('route_optimisation', 'routepoint')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    hub_ct = ContentType.objects.get_for_model(Hub, for_concrete_model=False)
    order_ct = ContentType.objects.get_for_model(Order, for_concrete_model=False)
    location_ct = ContentType.objects.get_for_model(DriverRouteLocation, for_concrete_model=False)

    RoutePoint.objects.update(point_kind=models.Case(
        models.When(point_content_type=hub_ct, then=models.Value(RoutePointModel.POINT_KIND.hub,
                                                                 output_field=models.CharField())),
        models.When(point_content_type=order_ct, then=models.Value(RoutePointModel.POINT_KIND.delivery,
                                                                   output_field=models.CharField())),
        models.When(point_content_type=location_ct, then=models.Value(RoutePointModel.POINT_KIND.location,
                                                                      output_field=models.CharField())),
        default=models.Value(RoutePointModel.POINT_KIND.delivery,
                             output_field=models.CharField()),
    ))


class Migration(migrations.Migration):

    dependencies = [
        ('route_optimisation', '0007_auto_20210310_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='routepoint',
            name='point_kind',
            field=models.CharField(choices=[('hub', 'Hub'), ('location', 'Location'), ('pickup', 'Pickup'), ('delivery', 'Delivery')], max_length=12, null=True),
        ),
        migrations.RunPython(set_field_value, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='routepoint',
            name='point_kind',
            field=models.CharField(
                choices=[('hub', 'Hub'), ('location', 'Location'), ('pickup', 'Pickup'), ('delivery', 'Delivery'),
                         ('break', 'Break')], max_length=12),
        ),
    ]
