# Generated by Django 2.2.5 on 2021-07-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_optimisation', '0008_routepoint_point_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='routepoint',
            name='start_time_known_to_customer',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
