# Generated by Django 2.2.5 on 2022-02-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_optimisation', '0009_routepoint_start_time_known_to_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routepoint',
            name='utilized_capacity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
