# Generated by Django 2.2.5 on 2022-05-23 16:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import route_optimisation.logging.log_handler
import route_optimisation.models.engine_run


class Migration(migrations.Migration):

    dependencies = [
        ('route_optimisation', '0012_remove_routeoptimisation_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('state', models.CharField(choices=[('ENGINE_CREATED', 'Created'), ('ENGINE_OPTIMISING', 'Optimising'), ('ENGINE_COMPLETED', 'Completed'), ('ENGINE_FAILED', 'Failed')], default='ENGINE_CREATED', max_length=20)),
                ('engine_options', route_optimisation.models.engine_run.EngineOptionsField(blank=True, default=dict)),
                ('result', route_optimisation.models.engine_run.EngineResultField(blank=True, default=dict)),
                ('engine_log', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='route_optimisation.ROLog')),
                ('optimisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_runs', to='route_optimisation.RouteOptimisation')),
            ],
            options={
                'abstract': False,
            },
            bases=(route_optimisation.logging.log_handler.ROLogGetter, models.Model),
        ),
    ]
