# Generated by Django 2.2.5 on 2022-06-28 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('route_optimisation', '0013_enginerun'),
    ]

    operations = [
        migrations.AddField(
            model_name='routepoint',
            name='next_point',
            field=models.ForeignKey(blank=True,
                                    help_text='Reflects the actual next point the driver went to. Some waypoints may be skipped by the driver as they were completed prematurely.',
                                    null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='past_point',
                                    to='route_optimisation.RoutePoint'),
        ),
    ]
