# Generated by Django 2.2.5 on 2022-07-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_optimisation', '0014_routepoint_next_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeoptimisation',
            name='is_removing_currently',
            field=models.BooleanField(default=False),
        ),
    ]
