# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-31 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0009_auto_20150515_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotificationsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('fcm_key', models.CharField(blank=True, max_length=512)),
                ('gcm_key', models.CharField(blank=True, max_length=512)),
                ('gcm_max_recipients', models.PositiveIntegerField(default=1000)),
                ('fcm_max_recipients', models.PositiveIntegerField(default=1000)),
                ('gcm_error_timeout', models.PositiveIntegerField(default=0)),
                ('fcm_error_timeout', models.PositiveIntegerField(default=0)),
                ('gcm_post_url', models.URLField(default='https://gcm-http.googleapis.com/gcm/send')),
                ('fcm_post_url', models.URLField(default='https://fcm.googleapis.com/fcm/send')),
            ],
            options={'verbose_name_plural': 'Notifications settings'},
        ),
        migrations.AddField(
            model_name='gcmdevice',
            name='cloud_provider',
            field=models.CharField(choices=[('GCM', 'GCM'), ('FCM', 'FCM')], default='GCM', max_length=16),
        ),
    ]
