# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 07:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0010_auto_20170331_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='updated_at',
            new_name='date_updated',
        ),
        migrations.RemoveField(
            model_name='gcmdevice',
            name='cloud_provider',
        ),
        migrations.AddField(
            model_name='device',
            name='application_id',
            field=models.CharField(blank=True, help_text='Opaque application identity, should be filled in for multiple key/certificate access', max_length=64, null=True, verbose_name='Application ID'),
        ),
        migrations.AddField(
            model_name='gcmdevice',
            name='cloud_message_type',
            field=models.CharField(choices=[('FCM', 'Firebase Cloud Message'), ('GCM', 'Google Cloud Message')], default='GCM', help_text='You should choose FCM or GCM', max_length=3, verbose_name='Cloud Message Type'),
        ),
        migrations.AlterField(
            model_name='pushnotificationssettings',
            name='fcm_max_recipients',
            field=models.PositiveIntegerField(default=1000, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
