# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0011_auto_20170503_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotificationssettings',
            name='apns_topic',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
