# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-06 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0012_pushnotificationssettings_apns_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apnsdevice',
            name='registration_id',
            field=models.CharField(max_length=256, unique=True, verbose_name='Registration ID'),
        ),
    ]
