# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-31 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0063_auto_20180109_2203'),
        ('notification', '0015_auto_20170926_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=40)),
                ('text', models.TextField()),
                ('sender', models.CharField(max_length=40)),
                ('segment_count', models.PositiveSmallIntegerField()),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.Merchant')),
            ],
        ),
    ]
