# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-31 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0016_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='merchant.Merchant'),
        ),
    ]
