# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-08 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0019_auto_20180208_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='merchant',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
