# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0021_auto_20180215_0457'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='smsmessage',
        #     name='price',
        #     field=models.FloatField(default=0),
        # ),
    ]
