# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 07:54
from __future__ import unicode_literals

from django.db import migrations, models


def add_price_to_sms(apps, schema_editor):
    DEFAULT_SMS_COST = 0.15

    MerchantSMSMessage = apps.get_model('merchant', 'MerchantSMSMessage')
    merchant_messages = MerchantSMSMessage.objects.filter(is_sent=True)
    for sms in merchant_messages:
        sms.price = sms.segment_count * (sms.merchant.sms_price or DEFAULT_SMS_COST)
        sms.save()

    OrderSMSMessage = apps.get_model('tasks', 'OrderSMSMessage')
    job_messages = OrderSMSMessage.objects.filter(is_sent=True)
    for sms in job_messages:
        sms.price = sms.segment_count * (sms.order.merchant.sms_price or DEFAULT_SMS_COST)
        sms.save()


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0022_smsmessage_price'),
        ('merchant', '0067_merge_20180308_0107'),
        ('tasks', '0105_merge_20180308_0107')
    ]

    operations = [
        # migrations.RunPython(add_price_to_sms, migrations.RunPython.noop),
    ]
