# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0023_price_for_sms_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='api_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
