# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-10 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0024_device_api_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apnsdevice',
            name='device_id',
            field=models.CharField(db_index=True, help_text='UDID / UIDevice.identifierForVendor()', max_length=255, null=True, unique=True, verbose_name='Device ID'),
        ),
        migrations.AlterField(
            model_name='gcmdevice',
            name='device_id',
            field=models.CharField(db_index=True, help_text='ANDROID_ID / TelephonyManager.getDeviceId() (always as hex)', max_length=255, null=True, unique=True, verbose_name='Device ID'),
        ),
    ]
