# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-10 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0024_device_api_version'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='smsmessage',
        #     old_name='sent_at',
        #     new_name='dispatched_at',
        # ),
    ]
