# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 09:45
from __future__ import unicode_literals

from django.db import migrations


def migrate_devices(apps, schema_editor):
    Device = apps.get_model('notification', 'Device')
    Device.objects.filter(user__isnull=False).update(in_use=True)
    Device.objects.filter(user__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0025_auto_20180411_0220'),
    ]

    operations = [
        migrations.RunPython(code=migrate_devices, reverse_code=migrations.RunPython.noop)
    ]
