# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-12 11:48
from __future__ import unicode_literals

from django.db import migrations, models


def is_sent_migration(apps, schema_migration):
    SmsMessage = apps.get_model('notification.smsmessage')
    SmsMessage.objects.filter(is_sent=True).update(sent_at=models.F('dispatched_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0026_auto_20180410_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotificationssettings',
            name='fcm_error_timeout',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='pushnotificationssettings',
            name='gcm_error_timeout',
            field=models.PositiveIntegerField(default=7),
        ),
        # migrations.RunPython(code=is_sent_migration),
        # migrations.RemoveField(
        #     model_name='smsmessage',
        #     name='is_sent',
        # ),
    ]
