# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-14 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0027_auto_20180412_2148'),
        ('notification', '0026_auto_20180411_1945'),
    ]

    operations = [
    ]
