# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-30 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0079_merge_20180523_2141'),
        ('tasks', '0107_merge_20180322_1914'),
        ('notification', '0028_merge_20180414_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantMessageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('html_text', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('template_type', models.IntegerField(choices=[(0, 'Another'), (1, 'Customer job started'), (2, 'Customer job terminated'), (3, 'Follow up'), (4, 'Follow up reminder'), (5, 'Driver job started'), (6, 'Complete invitation'), (7, 'invitation'), (8, 'Confirm account'), (9, 'Reset password'), (10, 'Billing'), (11, 'Account locked')], default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('use_default', models.BooleanField(default=True)),
                ('merchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='merchant.Merchant')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateSMSMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(null=True)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=40)),
                ('sender', models.CharField(default='Radaro', max_length=40)),
                ('segment_count', models.PositiveSmallIntegerField()),
                ('response_data', models.TextField()),
                ('price', models.FloatField(default=0)),
                ('dispatched_at', models.DateTimeField(null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Order')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.MerchantMessageTemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateEmailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               to='notification.MerchantMessageTemplate')),
                ('html_text', models.TextField(blank=True)),
                ('subject', models.CharField(max_length=255, blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='merchantmessagetemplate',
            unique_together=set([('id', 'template_type')]),
        ),
    ]
