# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-06 09:58
from __future__ import unicode_literals

import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0109_auto_20180706_2258'),
        ('merchant', '0084_auto_20180706_2255'),
        ('notification', '0031_auto_20180530_2315'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='smsmessage',
        #     name='polymorphic_ctype',
        # ),
        # migrations.DeleteModel(
        #     name='SMSMessage',
        # )
    ]
