# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-30 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0032_auto_20180606_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templateemailmessage',
            options={'verbose_name': 'Email message', 'verbose_name_plural': 'Email messages'},
        ),
        migrations.AlterModelOptions(
            name='templatesmsmessage',
            options={'verbose_name': 'SMS message', 'verbose_name_plural': 'SMS messages'},
        ),
        migrations.AlterField(
            model_name='merchantmessagetemplate',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='enable notification'),
        ),
        migrations.AlterField(
            model_name='merchantmessagetemplate',
            name='html_text',
            field=models.TextField(blank=True, verbose_name='email text'),
        ),
        migrations.AlterField(
            model_name='merchantmessagetemplate',
            name='subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='email subject'),
        ),
        migrations.AlterField(
            model_name='merchantmessagetemplate',
            name='template_type',
            field=models.IntegerField(choices=[(0, 'Another'), (1, 'Customer job started'), (2, 'Customer job terminated'), (3, 'Reminder (1h)'), (4, 'Reminder (24h)'), (5, 'Driver job started'), (6, 'Complete invitation'), (7, 'Invitation'), (8, 'Confirm account'), (9, 'Reset password'), (10, 'Billing'), (11, 'Account locked')], default=0),
        ),
        migrations.AlterField(
            model_name='merchantmessagetemplate',
            name='text',
            field=models.TextField(verbose_name='sms text'),
        ),
    ]
