# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-31 09:41
from __future__ import unicode_literals

from django.db import migrations
from django.template.loader import get_template

from notification.mixins import MessageTemplateStatus


def add_low_feedback_migration(apps, schema_editor):
    Merchant = apps.get_model('merchant', 'Merchant')
    MerchantMessageTemplate = apps.get_model('notification', 'MerchantMessageTemplate')

    template_type = MessageTemplateStatus.LOW_FEEDBACK
    template_name = MessageTemplateStatus.template_names_map.get(template_type)
    text = get_template(template_name + '.txt').template.source
    html_text = get_template(template_name + '.html').template.source
    subject = get_template(template_name + '.subject').template.source

    for merchant in Merchant.objects.exclude(templates__template_type=template_type):
        MerchantMessageTemplate.objects.create(template_type=template_type, text=text, html_text=html_text,
                                               subject=subject, enabled=False, merchant=merchant)


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0033_auto_20180730_2317'),
        ('merchant', '0086_auto_20180731_1848'),
    ]

    operations = [
        migrations.RunPython(add_low_feedback_migration, reverse_code=migrations.RunPython.noop)
    ]
