# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-30 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import radaro_utils.radaro_phone.models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0034_auto_20180731_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantmessagetemplate',
            name='template_type',
            field=models.IntegerField(choices=[(0, 'Another'), (1, 'Customer job started'), (2, 'Customer job terminated'), (3, 'Reminder (1h)'), (4, 'Reminder (24h)'), (5, 'Driver job started'), (6, 'Complete invitation'), (7, 'Invitation'), (8, 'Confirm account'), (9, 'Reset password'), (10, 'Billing'), (11, 'Account locked'), (12, 'Low customer feedback')], default=0),
        ),
        migrations.AlterField(
            model_name='templatesmsmessage',
            name='phone',
            field=radaro_utils.radaro_phone.models.PhoneField(max_length=128),
        ),
    ]
