# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 09:31
from __future__ import unicode_literals

from django.db import migrations
from django.template.loader import get_template

from notification.mixins.template_status import MessageTemplateStatus


def change_low_feedback_default_template(apps, schema_editor):
    MerchantMessageTemplate = apps.get_model('notification', 'MerchantMessageTemplate')
    templates = MerchantMessageTemplate.objects.filter(template_type=MessageTemplateStatus.LOW_FEEDBACK)

    template_name = MessageTemplateStatus.template_names_map.get(MessageTemplateStatus.LOW_FEEDBACK)
    text = get_template(template_name + '.txt').template.source
    html_text = get_template(template_name + '.html').template.source
    subject = get_template(template_name + '.subject').template.source

    templates.update(
        text=text,
        html_text=html_text,
        subject=subject
    )


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0034_auto_20180731_1941'),
    ]

    operations = [
        migrations.RunPython(code=change_low_feedback_default_template, reverse_code=migrations.RunPython.noop)
    ]