# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-29 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0029_auto_20180530_2204'),
        ('notification', '0034_auto_20180731_1941'),
    ]

    operations = [
    ]
