# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-07 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0034_upcoming_delivery_sms'),
        ('notification', '0035_auto_20180904_1931'),
    ]

    operations = [
    ]
