# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0035_auto_20180830_1918'),
        ('notification', '0035_merge_20180830_0024'),
    ]

    operations = [
    ]
