# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-28 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0036_auto_20180915_0154'),
        ('notification', '0037_auto_20180907_1934'),
    ]

    operations = [
    ]
