# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-06 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0035_auto_20180904_1931'),
        ('notification', '0037_auto_20180904_2150'),
    ]

    operations = [
    ]
