# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0038_merge_20180907_0612'),
        ('notification', '0036_auto_20180915_0154'),
    ]

    operations = [
    ]
