# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0039_merge_20180915_0204'),
        ('notification', '0039_auto_20180928_2048'),
    ]

    operations = [
    ]
