# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-26 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0040_update_upcoming_delivery_templates'),
        ('notification', '0041_weekly_reports_instance'),
    ]

    operations = [
    ]
