# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-08 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0042_merge_20181026_2302'),
        ('notification', '0040_auto_20181010_0037'),
    ]

    operations = [
    ]
