# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-26 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0042_merge_20181026_2302'),
        ('notification', '0042_auto_20181015_2243'),
    ]

    operations = [
    ]
