# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-16 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0043_merge_20181027_0139'),
        ('notification', '0043_merge_20181108_2306'),
    ]

    operations = [
    ]
