# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-11 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import radaro_utils.files.utils


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0046_auto_20181203_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateEmailAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=radaro_utils.files.utils.UUIDPathGenerator())),
                ('email_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.TemplateEmailMessage')),
            ],
        ),
        migrations.AlterField(
            model_name='merchantmessagetemplate',
            name='template_type',
            field=models.IntegerField(choices=[(0, 'Another'), (1, 'Customer job started'), (2, 'Customer job terminated'), (3, 'Reminder (1h)'), (4, 'Reminder (24h)'), (5, 'Driver job started'), (6, 'Complete invitation'), (7, 'Invitation'), (8, 'Confirm account'), (9, 'Reset password'), (10, 'Billing'), (11, 'Account locked'), (12, 'Low customer feedback'), (13, 'Upcoming delivery'), (14, 'Weekly Radaro usage report'), (15, 'Advanced completion'), (16, 'Jobs daily report'), (17, 'Proof of delivery report')], default=0),
        ),
    ]
