# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-11 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0048_auto_20181211_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantmessagetemplate',
            name='template_type',
            field=models.IntegerField(choices=[(0, 'Another'), (1, 'Customer job started'), (2, 'Customer job terminated'), (3, 'Reminder (1h)'), (4, 'Reminder (24h)'), (5, 'Driver job started'), (6, 'Complete invitation'), (7, 'Invitation'), (8, 'Confirm account'), (9, 'Reset password'), (10, 'Billing'), (11, 'Account locked'), (12, 'Low customer feedback'), (13, 'Upcoming delivery'), (14, 'Weekly Radaro usage report'), (15, 'Advanced completion'), (16, 'Jobs daily report'), (17, 'Proof of delivery report'), (18, 'Start of Day checklist answer issue')], default=0),
        ),
        migrations.AlterField(
            model_name='templateemailattachment',
            name='email_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='notification.TemplateEmailMessage'),
        ),
    ]
