# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-05 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0050_auto_20190111_2138'),
        ('notification', '0049_auto_20181228_2250'),
    ]

    operations = [
    ]
