# Generated by Django 2.2.5 on 2020-02-07 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0052_auto_20190809_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatesmsmessage',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.Order'),
        ),
    ]
