# Generated by Django 2.2.5 on 2020-02-18 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0053_auto_20200208_0048'),
        ('notification', '0053_auto_20200215_0008'),
    ]

    operations = [
    ]
