# Generated by Django 2.2.5 on 2020-03-13 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0054_merge_20200312_2055'),
        ('notification', '0054_merge_20200218_1925'),
    ]

    operations = [
    ]
