# Generated by Django 2.2.5 on 2020-04-24 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0055_auto_20200408_2342'),
        ('notification', '0055_merge_20200313_1903'),
    ]

    operations = [
    ]
