# Generated by Django 2.2.5 on 2020-11-24 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0056_auto_20200918_2113'),
        ('notification', '0056_merge_20200424_2148'),
    ]

    operations = [
    ]
