# Generated by Django 2.2.5 on 2021-07-30 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0057_auto_20210729_2229'),
        ('notification', '0057_merge_20201124_2301'),
    ]

    operations = [
    ]
