# Generated by Django 2.2.5 on 2022-08-02 07:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('notification', '0058_auto_20220726_2038'),
        ('notification', '0058_merge_20210731_0014'),
    ]

    operations = [
    ]
