# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event',
            field=models.IntegerField(choices=[(-1, 'deleted'), (0, 'created'), (1, 'changed')], default=0),
        ),
    ]
