# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_event_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='field',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
