# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_auto_20160215_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
