# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-14 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_event_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='obj_dump',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='event',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
