# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-15 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0012_merchant_is_blocked'),
        ('reporting', '0005_auto_20160414_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='merchant.Merchant'),
        ),
    ]
