# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-25 10:20
from __future__ import unicode_literals

from django.db import migrations, models

import radaro_utils.files.utils


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0007_exportreportinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportreportinstance',
            name='file',
            field=models.FileField(null=True, upload_to=radaro_utils.files.utils.delayed_task_upload),
        ),
    ]
