# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-20 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0008_auto_20160725_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event',
            field=models.IntegerField(choices=[(-1, 'deleted'), (0, 'created'), (1, 'changed'), (2, 'model_changed')], default=0),
        ),
    ]
