# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-04 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0009_auto_20161020_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='new_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
