# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-17 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0011_auto_20170511_0253'),
        ('reporting', '0011_auto_20170414_1703'),
    ]

    operations = [
    ]
