# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-08 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0013_exportreportinstance_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportreportinstance',
            options={'ordering': ('-id',)},
        ),
    ]
