# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-18 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0014_auto_20170709_0543'),
        ('reporting', '0014_auto_20170708_2133'),
    ]

    operations = [
    ]
