# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 10:48
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0016_auto_20180108_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='detailed_dump',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
