# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 14:57
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import django_fsm
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0018_remove_exportreportinstance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportreportinstance',
            name='created_at',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='exportreportinstance',
            name='status',
            field=django_fsm.FSMField(default='created', max_length=50),
        ),
        migrations.RenameField(
            model_name='exportreportinstance',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AddField(
            model_name='exportreportinstance',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                           verbose_name='modified'),
        ),
    ]
