# Generated by Django 2.2.5 on 2020-07-29 12:51

import django.core.serializers.json
from django.db import migrations
import schedule.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule',
            field=schedule.fields.ScheduleField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
