# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='location',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=None, max_length=63),
        ),
    ]
