# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-09 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0002_auto_20160203_1520'),
        ('tasks', '0015_auto_20160309_0800'),
        ('merchant', '0004_remove_merchant_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
