# Generated by Django 2.2.5 on 2020-05-18 07:24

from django.db import migrations, models
import django.db.models.deletion
import radaro_utils.files.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0137_auto_20200306_2251'),
        ('merchant', '0125_merge_20200506_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.Merchant')),
            ],
            options={
                'ordering': ('id',),
                'unique_together': {('name', 'merchant')},
            },
        ),
        migrations.CreateModel(
            name='OrderConfirmationDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=radaro_utils.files.utils.UUIDPathGenerator())),
                ('name', models.CharField(max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_confirmation_documents', to='tasks.Order')),
                ('tags', models.ManyToManyField(blank=True, related_name='order_confirmation_documents', to='documents.Tag')),
            ],
        ),
    ]
