# Generated by Django 2.2.5 on 2020-06-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconfirmationdocument',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
