# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_extension', '0002_auto_20170413_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='merchant_extension.Question'),
        ),
        migrations.AlterField(
            model_name='resultchecklist',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='merchant_extension.Checklist'),
        ),
    ]
