# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-07 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_extension', '0003_auto_20170526_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Answer to checklist question', 'verbose_name_plural': 'Answers to checklists questions'},
        ),
        migrations.AlterModelOptions(
            name='resultchecklist',
            options={'verbose_name': 'Checklist Result', 'verbose_name_plural': 'Checklist Results'},
        ),
    ]
