# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-10 11:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import radaro_utils.files.utils
import radaro_utils.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchant_extension', '0003_auto_20170526_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=radaro_utils.files.utils.UUIDPathGenerator())),
            ],
            bases=(radaro_utils.models.ResizeImageMixin, models.Model),
        ),
        migrations.CreateModel(
            name='JobChecklist',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('merchant_extension.checklist',),
        ),
        migrations.CreateModel(
            name='StartOfDayChecklist',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('merchant_extension.checklist',),
        ),
        migrations.AddField(
            model_name='answer',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='checklist_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Job Checklist'), (2, 'Start of Day Checklist')], default=1),
        ),
        migrations.AddField(
            model_name='resultchecklist',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerphoto',
            name='answer_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='merchant_extension.Answer'),
        ),
    ]
