# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-14 08:42
from __future__ import unicode_literals

from django.db import migrations, models


def fill_created_at(apps, schema_editor):
    ResultChecklist = apps.get_model('merchant_extension', 'resultchecklist')
    ResultChecklist.objects.update(created_at=models.F('date_of_risk_assessment'))


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_extension', '0005_resultchecklist_created_at'),
    ]

    operations = [
        migrations.RunPython(fill_created_at, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='resultchecklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
