# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_extension', '0004_auto_20190208_0132'),
        ('merchant_extension', '0006_auto_20190114_1942'),
    ]

    operations = [
    ]
