# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-19 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import radaro_utils.files.utils
import radaro_utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_extension', '0007_merge_20190208_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('is_checkbox', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ResultChecklistAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('question_answer', models.ForeignKey(blank=True, related_name='result_answers', to='merchant_extension.QuestionAnswer', on_delete=models.CASCADE)),
                ('result_checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_answers', to='merchant_extension.ResultChecklist')),
            ],
            options={'verbose_name': 'Answer to checklist question',
                     'verbose_name_plural': 'Answers to checklists questions'},
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='merchant_extension.Checklist')),
                ('consecutive_number', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='ResultChecklistAnswerPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=radaro_utils.files.utils.UUIDPathGenerator())),
                ('answer_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos',
                                                    to='merchant_extension.ResultChecklistAnswer')),
            ],
            options={
                'abstract': False,
            },
            bases=(radaro_utils.models.ResizeImageMixin, models.Model),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('dichotomous', 'Dichotomous Question'), ('multiple_choice', 'Multiple Choice Question'), ('single_choice', 'Single Choice Question'), ('text', 'Text Question'), ('scale', 'Scale Question')], default='dichotomous', max_length=50),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='merchant_extension.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='merchant_extension.Section'),
        ),
        migrations.AddField(
            model_name='question',
            name='subtitles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list,
                                                            size=None, blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='resultchecklistanswer',
            unique_together=set([('question_answer', 'result_checklist')])
        ),
        migrations.AlterField(
            model_name='checklist',
            name='checklist_type',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'Job Checklist'), (2, 'Start of Day Checklist'), (3, 'Survey')], db_index=True, default=1),
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('merchant_extension.checklist',),
        ),
        migrations.CreateModel(
            name='SurveyResult',
            fields=[
            ],
            options={
                'verbose_name': 'Survey Result',
                'proxy': True,
                'verbose_name_plural': 'Survey Results',
                'indexes': [],
            },
            bases=('merchant_extension.resultchecklist',),
        )
    ]
