# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-20 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_extension', '0009_auto_20190319_2029'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='result_checklist',
        ),
        migrations.RemoveField(
            model_name='answerphoto',
            name='answer_object',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='AnswerPhoto',
        ),
    ]
