# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-20 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_extension', '0010_auto_20190320_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultchecklistanswer',
            old_name='question_answer',
            new_name='answer',
        ),
        migrations.AlterUniqueTogether(
            name='resultchecklistanswer',
            unique_together=set([('answer', 'result_checklist')]),
        ),
        migrations.AlterField(
            model_name='resultchecklistanswer',
            name='answer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='result_checklist_answers', to='merchant_extension.QuestionAnswer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='questions', to='merchant_extension.Checklist'),
        ),
        migrations.RenameModel(
            old_name='QuestionAnswer',
            new_name='Answer',
        ),
    ]
