# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-10 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_extension', '0012_auto_20190410_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('section', 'consecutive_number')},
        ),
        migrations.RemoveField(
            model_name='question',
            name='checklist',
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='merchant_extension.Section'),
        ),
    ]
