# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-16 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Subquery, OuterRef


def add_questions_to_result_checklist_answers(apps, schema_editor):
    ResultChecklistAnswer = apps.get_model('merchant_extension', 'ResultChecklistAnswer')
    ResultChecklistAnswer.objects.update(
        question=Subquery(ResultChecklistAnswer.objects.filter(pk=OuterRef('pk')).values('answer__question')[:1])
    )


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_extension', '0013_auto_20190410_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultchecklistanswer',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='result_checklist_answers', to='merchant_extension.Answer'),
        ),
        migrations.AddField(
            model_name='resultchecklistanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_answers',
                                    to='merchant_extension.Question', null=True, blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='resultchecklistanswer',
            unique_together=set([('question', 'answer', 'result_checklist')]),
        ),
        migrations.RunPython(add_questions_to_result_checklist_answers, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='resultchecklistanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_answers',
                                    to='merchant_extension.Question'),
        ),

    ]
