# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-17 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_extension', '0015_auto_20190418_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('dichotomous', 'Dichotomous'), ('multiple_choice', 'Multiple Choice (Multi-Selection)'), ('single_choice', 'Multiple Choice (Single-Selection)'), ('text', 'Text Response'), ('scale', 'NPS & Scale Slider')], default='dichotomous', max_length=50),
        )
    ]
