# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-23 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_extension', '0016_auto_20190617_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('id',)},
        ),
    ]
