# Generated by Django 2.2.5 on 2020-07-09 13:58

import base.utils.path_generators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_extension', '0017_auto_20190823_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultchecklistanswerphoto',
            name='thumb_image_100x100_field',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=base.utils.path_generators.ThumbnailsUploadPath()),
        ),
        migrations.AddField(
            model_name='resultchecklistconfirmationphoto',
            name='thumb_image_100x100_field',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=base.utils.path_generators.ThumbnailsUploadPath()),
        ),
    ]
