# Generated by Django 2.2.5 on 2022-03-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_extension', '0018_auto_20200709_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='photos_required',
            field=models.BooleanField(default=False, verbose_name='Photos must be attached'),
        ),
    ]
