# Generated by Django 2.2.5 on 2022-04-22 10:23

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):
    dependencies = [
        ('merchant_extension', '0019_answer_photos_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(default=None, max_length=63)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('happened_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='resultchecklistanswerphoto',
            name='happened_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='resultchecklistanswerphoto',
            name='image_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='merchant_extension.ImageLocation'),
        ),
    ]
