# Generated by Django 2.2.5 on 2022-07-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('merchant_extension', '0020_auto_20220422_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndOfDayChecklist',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('merchant_extension.checklist',),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='checklist_type',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'Job Checklist'), (2, 'Start of Day Checklist'), (3, 'Survey'),
                         (4, 'End of Day Checklist')], db_index=True, default=1),
        ),
    ]
