# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-04 09:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('tasks', '0001_initial'), ('tasks', '0002_auto_20160203_1538'), ('tasks', '0003_auto_20160205_0833'), ('tasks', '0004_auto_20160205_0837'), ('tasks', '0005_auto_20160205_1042')]

    initial = True

    dependencies = [
        ('routing', '0002_auto_20160203_1520'),
        ('base', '0009_auto_20160203_1530'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=40, null=True)),
                ('description', models.TextField()),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routing.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('pickup_from', models.DateTimeField(auto_now_add=True)),
                ('pickup_before', models.DateTimeField()),
                ('deliver_from', models.DateTimeField(auto_now_add=True)),
                ('deliver_before', models.DateTimeField()),
                ('status', models.CharField(blank=True, choices=[('failed', 'Failed'), ('rejected', 'Rejected'), ('created', 'Created'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('delivered', 'Delivered'), ('confirmed', 'Confirmed')], max_length=20, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Customer')),
                ('deliver_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliver', to='routing.Location')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='merchant.Merchant')),
                ('pickup_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup', to='routing.Location')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routing.Location'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routing.Location'),
        ),
    ]
