# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-28 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0043_order_deleted_squashed_0055_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='geofence_entered',
            field=models.NullBooleanField(),
        ),
    ]
