# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-16 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tasks', '0056_order_geofence_entered'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=250)),
                ('extra', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_id', models.PositiveIntegerField()),
                ('source_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='externaljob',
            unique_together=set([('external_id', 'source_id', 'source_type')]),
        ),
    ]
