# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-16 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def external_job_models_migration(apps, schema_editor):
    ExternalJob = apps.get_model('tasks', 'ExternalJob')
    WebhooksExternalJob = apps.get_model('webhooks', 'ExternalJob')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    MerchantAPIKey = apps.get_model('webhooks', 'MerchantAPIKey')
    Order = apps.get_model('tasks', 'Order')

    for job in WebhooksExternalJob.objects.all():
        new_job = ExternalJob()
        new_job.external_id = job.external_id
        new_job.extra = job.extra
        new_job.source_id = job.api_key_id
        new_job.source_type = ContentType.objects.get_for_model(MerchantAPIKey)
        new_job.created_at = job.created_at
        new_job.save()

        Order.objects.filter(external_job_id=job.id).update(_external_job_id=new_job.id)


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0057_auto_20161116_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='_external_job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_order', to='tasks.ExternalJob'),
        ),
        migrations.RunPython(external_job_models_migration, reverse_code=migrations.RunPython.noop),
    ]
