# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0057_auto_20161117_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not_assigned', 'Not assigned'), ('assigned', 'Assigned'), ('go_to_pick_up', 'Go to pick up'), ('picked_up', 'Picked up'), ('in_progress', 'In progress'), ('delivered', 'Completed'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='not_assigned', max_length=20),
        ),
    ]
