# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-16 12:22
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations
from django.db import models


def reverse_external_job_rename_migration(apps, schema_editor):
    Order = apps.get_model('tasks', 'Order')
    ExternalJob = apps.get_model('tasks', 'ExternalJob')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    MerchantAPIKey = apps.get_model('webhooks', 'MerchantAPIKey')
    WebhooksExternalJob = apps.get_model('webhooks', 'ExternalJob')

    content_type = ContentType.objects.get_for_model(MerchantAPIKey)

    for job in ExternalJob.objects.filter(source_type=content_type):
        api_key = MerchantAPIKey.objects.get(id=job.source_id)
        webhook_job = WebhooksExternalJob.objects.filter(external_id__iexact=job.external_id, api_key=api_key).first()
        Order.objects.filter(_external_job_id=job.id).update(external_job_id=webhook_job.id)


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0058_order__external_job'),
    ]
    operations = [
        migrations.RunPython(code=migrations.RunPython.noop, reverse_code=reverse_external_job_rename_migration),
        migrations.RemoveField(model_name='order', name='external_job'),
        migrations.RenameField(model_name='order', old_name='_external_job', new_name='external_job'),
        migrations.AlterField(
            model_name='order',
            name='external_job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='order', to='tasks.ExternalJob'),
        )
    ]

