# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-21 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0059_auto_20161116_2322'),
        ('tasks', '0058_auto_20161117_2014'),
    ]

    operations = [
    ]
