# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-04 09:58
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# tasks.migrations.0067_auto_20170105_2305

class Migration(migrations.Migration):

    replaces = [('tasks', '0060_auto_20161121_2003'), ('tasks', '0059_remove_order_weight'), ('tasks', '0061_merge_20161205_2325'), ('tasks', '0062_auto_20161205_2335'), ('tasks', '0063_auto_20161205_2341'), ('tasks', '0064_auto_20161212_2145'), ('tasks', '0065_auto_20161212_2200'), ('tasks', '0066_order_time_inside_geofence'), ('tasks', '0067_auto_20170105_2305'), ('tasks', '0068_auto_20170106_0131'), ('tasks', '0069_auto_20170106_0132'), ('tasks', '0070_auto_20170106_1838'), ('tasks', '0071_order_real_path'), ('tasks', '0072_order_description')]

    dependencies = [
        ('tasks', '0059_customer_merchant'),
        ('tasks', '0060_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='weight',
        ),
        migrations.AlterField(
            model_name='customer',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='merchant.Merchant'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='merchant.Merchant'),
        ),
        migrations.AlterModelOptions(
            name='orderlocation',
            options={'ordering': ('timestamp',)},
        ),
        migrations.AlterUniqueTogether(
            name='orderlocation',
            unique_together=set([('location', 'address')]),
        ),
        migrations.AddField(
            model_name='order',
            name='time_inside_geofence',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.OrderLocation'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='merchant.Merchant'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='merchant.Merchant'),
        ),
        migrations.AddField(
            model_name='order',
            name='real_path',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
