# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-04 09:28
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# tasks.migrations.0075_auto_20170206_2206
# tasks.migrations.0077_auto_20170322_0007
# tasks.migrations.0081_externaljob_processed
# tasks.migrations.0095_auto_20170829_1844
# tasks.migrations.0104_auto_20180207_0019
import radaro_utils.files.utils
import radaro_utils.models

class Migration(migrations.Migration):

    replaces = [('tasks', '0073_order_sub_branding'), ('tasks', '0074_order_time_at_job'), ('tasks', '0075_auto_20170206_2206'), ('tasks', '0076_orderconfirmationphoto'), ('tasks', '0077_auto_20170322_0007'), ('tasks', '0078_auto_20170408_0005'), ('tasks', '0076_auto_20170324_0220'), ('tasks', '0079_merge'), ('tasks', '0080_auto_20170411_0208'), ('tasks', '0081_externaljob_processed'), ('tasks', '0076_bulkdelayedupload_instances'), ('tasks', '0082_merge'), ('tasks', '0083_auto_20170427_2127'), ('tasks', '0084_auto_20170428_0128'), ('tasks', '0085_bulkdelayedupload_instances'), ('tasks', '0076_order_driver_checklist'), ('tasks', '0086_merge_20170506_2349'), ('tasks', '0082_auto_20170414_1703'), ('tasks', '0087_merge_20170526_1959'), ('tasks', '0088_order_is_completed_by_geofence'), ('tasks', '0089_readable_locations_presentation'), ('tasks', '0086_auto_20170511_2217'), ('tasks', '0087_bulkdelayedupload_original_file_name'), ('tasks', '0089_merge_20170620_0059'), ('tasks', '0090_merge_20170627_2353'), ('tasks', '0091_bulkdelayedupload_method'), ('tasks', '0092_auto_20170709_0543'), ('tasks', '0091_order_changed_in_offline'), ('tasks', '0093_merge_20170818_2159'), ('tasks', '0091_auto_20170729_0139'), ('tasks', '0094_merge_20170824_0002'), ('tasks', '0095_auto_20170829_1844'), ('tasks', '0093_order_labels'), ('tasks', '0096_merge_20170901_2011'), ('tasks', '0097_auto_20170904_1527'), ('tasks', '0098_auto_20170906_1923'), ('tasks', '0091_order_serialized_track'), ('tasks', '0096_merge_20170905_1941'), ('tasks', '0099_merge_20170919_1845'), ('tasks', '0091_change_confirmed_status_to_field'), ('tasks', '0092_auto_20170803_1838'), ('tasks', '0100_merge_20170920_2330'), ('tasks', '0101_auto_20170920_2339'), ('tasks', '0102_remove_order_confirmation_photo'), ('tasks', '0102_order_geofence_entered_on_backend'), ('tasks', '0103_merge_20180110_0211'), ('tasks', '0104_ordersmsmessage'), ('tasks', '0104_auto_20180207_0019'), ('tasks', '0105_merge_20180308_0107')]

    dependencies = [
        ('merchant', '0051_merge_20170620_0059'),
        ('merchant_extension', '0001_initial'),
        ('merchant', '0054_auto_20170904_1527'),
        ('merchant', '0053_auto_20170809_1714'),
        ('notification', '0021_auto_20180215_0457'),
        ('merchant', '0037_auto_20170126_0048'),
        ('tasks', '0060_auto_20161121_2003_squashed_0072_order_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sub_branding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='merchant.SubBranding'),
        ),
        migrations.AddField(
            model_name='order',
            name='time_at_job',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OrderConfirmationPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=radaro_utils.files.utils.get_upload_path)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_confirmation_photos', to='tasks.Order')),
            ],
            bases=(radaro_utils.models.ResizeImageMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterModelOptions(
            name='orderlocation',
            options={'ordering': ('created_at',)},
        ),
        migrations.RenameField(
            model_name='orderlocation',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='bulk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='tasks.BulkDelayedUpload'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tasks.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliver_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliver', to='tasks.OrderLocation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='merchant.Merchant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pickup', to='tasks.OrderLocation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='starting_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='starting', to='tasks.OrderLocation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sub_branding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='merchant.SubBranding'),
        ),
        migrations.AddField(
            model_name='externaljob',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='external_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='tasks.ExternalJob'),
        ),
        migrations.AlterField(
            model_name='order',
            name='external_job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='tasks.ExternalJob'),
        ),
        migrations.AddField(
            model_name='bulkdelayedupload',
            name='instances',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_checklist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchant_extension.ResultChecklist'),
        ),
        migrations.AlterField(
            model_name='bulkdelayedupload',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchant.Merchant'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.OrderLocation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='is_completed_by_geofence',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='bulkdelayedupload',
            name='comment',
        ),
        migrations.AddField(
            model_name='bulkdelayedupload',
            name='log',
            field=jsonfield.fields.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='bulkdelayedupload',
            name='processed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulkdelayedupload',
            name='state_params',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkdelayedupload',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='bulkdelayedupload',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bulkdelayedupload',
            name='method',
            field=models.CharField(choices=[('web', 'WEB'), ('api', 'API'), ('no_info', 'No info')], default='no_info', max_length=10),
        ),
        migrations.AlterModelOptions(
            name='bulkdelayedupload',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='order',
            name='changed_in_offline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='ending_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ending', to='tasks.OrderLocation'),
        ),
        migrations.CreateModel(
            name='ErrorCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(blank=True, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_codes', to='merchant.Merchant')),
                ('is_comment_necessary', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='error_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='error_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.ErrorCode'),
        ),
        migrations.AddField(
            model_name='order',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='merchant.Label'),
        ),
        migrations.AddField(
            model_name='order',
            name='serialized_track',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='order',
            name='is_confirmed_by_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not_assigned', 'Not assigned'), ('assigned', 'Assigned'), ('go_to_pick_up', 'Go to pick up'), ('picked_up', 'Picked up'), ('in_progress', 'In progress'), ('delivered', 'Completed'), ('failed', 'Failed')], default='not_assigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not_assigned', 'Not assigned'), ('assigned', 'Assigned'), ('go_to_pick_up', 'Go to pick up'), ('picked_up', 'Picked up'), ('in_progress', 'In progress'), ('way_back', 'Way back'), ('delivered', 'Completed'), ('failed', 'Failed')], default='not_assigned', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='wayback_distance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='order',
            name='confirmation_photo',
        ),
        migrations.AddField(
            model_name='order',
            name='geofence_entered_on_backend',
            field=models.NullBooleanField(),
        ),
        # migrations.CreateModel(
        #     name='OrderSMSMessage',
        #     fields=[
        #         ('smsmessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notification.SMSMessage')),
        #         ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='tasks.Order')),
        #     ],
        #     options={
        #         'manager_inheritance_from_future': True,
        #     },
        #     bases=('notification.smsmessage',),
        # ),
        migrations.CreateModel(
            name='OrderPrice',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('tasks.order',),
        ),
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='serialized_track',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
