# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-09 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

import radaro_utils.models
import radaro_utils.files.utils


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0103_merge_20180110_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPreConfirmationPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=radaro_utils.files.utils.get_upload_path)),
            ],
            bases=(radaro_utils.models.ResizeImageMixin, models.Model),
        ),
        migrations.AddField(
            model_name='order',
            name='pre_confirmation_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pre_confirmation_signature',
            field=models.ImageField(blank=True, null=True, upload_to=radaro_utils.files.utils.get_upload_path),
        ),
        migrations.AddField(
            model_name='orderpreconfirmationphoto',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_confirmation_photos', to='tasks.Order'),
        ),
    ]
