# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-13 09:14
from __future__ import unicode_literals

import base.utils
from django.db import migrations, models

import radaro_utils.files.utils


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0104_auto_20180209_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pre_confirmation_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Pre-inspection comment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pre_confirmation_signature',
            field=models.ImageField(blank=True, null=True, upload_to=radaro_utils.files.utils.get_upload_path,
                                    verbose_name='Pre-inspection signature'),
        ),
    ]
