# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-19 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0064_merchant_use_success_codes'),
        ('tasks', '0104_terminatecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminatecode',
            name='type',
            field=models.CharField(choices=[('error', 'Error'), ('success', 'Success')], max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name='terminatecode',
            unique_together=set([('code', 'merchant')]),
        ),
    ]
