# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 09:48
from __future__ import unicode_literals

from django.core.files.base import ContentFile
from django.db import migrations
from django.db.models import Q


def move_result_checklist_confirmation_photos(apps, schema_editor):
    ResultChecklistConfirmationPhoto = apps.get_model('merchant_extension', 'ResultChecklistConfirmationPhoto')
    OrderPreConfirmationPhoto = apps.get_model('tasks', 'OrderPreConfirmationPhoto')
    photo_objects = []

    for confirmation_photo in ResultChecklistConfirmationPhoto.objects.filter(result_checklist__order__isnull=False):
        pre_confirmation_photo = OrderPreConfirmationPhoto()
        confirmation_photo_copy = ContentFile(confirmation_photo.image.read())
        confirmation_photo_copy.name = confirmation_photo.image.name.split('/')[-1]
        pre_confirmation_photo.image = confirmation_photo_copy
        pre_confirmation_photo.order = confirmation_photo.result_checklist.order
        photo_objects.append(pre_confirmation_photo)
    OrderPreConfirmationPhoto.objects.bulk_create(photo_objects)


def move_result_checklist_confirmation_signatures_and_comments(apps, schema_editor):
    ResultChecklist = apps.get_model('merchant_extension', 'ResultChecklist')

    for checklist in ResultChecklist.objects.filter(is_correct__isnull=False, order__isnull=False):
        if checklist.confirmation_signature:
            confirmation_signature_copy = ContentFile(checklist.confirmation_signature.read())
            confirmation_signature_copy.name = checklist.confirmation_signature.name.split('/')[-1]
            checklist.order.pre_confirmation_signature = confirmation_signature_copy
        if checklist.confirmation_comment:
            checklist.order.pre_confirmation_comment = checklist.confirmation_comment
        checklist.order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0105_auto_20180313_2014'),
    ]

    operations = [
        migrations.RunPython(move_result_checklist_confirmation_photos, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(move_result_checklist_confirmation_signatures_and_comments,
                             reverse_code=migrations.RunPython.noop)
    ]
