# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-20 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0105_auto_20180220_0228'),
        ('tasks', '0073_order_sub_branding_squashed_0105_merge_20180308_0107'),
    ]

    operations = [
    ]
