# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0106_merge_20180321_0049'),
        ('tasks', '0106_auto_20180321_2048'),
    ]

    operations = [
    ]
