# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-06 12:58
from __future__ import unicode_literals

from django.db import migrations


def reverse_delete_migration(apps, schema_editor):
    TemplateSMSMessage = apps.get_model('notification', 'TemplateSMSMessage')
    OrderSMSMessage = apps.get_model('tasks', 'OrderSMSMessage')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    for sms in TemplateSMSMessage.objects.filter(order__isnull=False):
        order_sms = OrderSMSMessage()
        order_sms.phone = sms.phone
        order_sms.message = sms.text
        order_sms.sender = sms.sender
        order_sms.segment_count = sms.segment_count
        order_sms.response_data = sms.response_data
        order_sms.price = sms.price
        order_sms.dispatched_at = sms.dispatched_at
        order_sms.sent_at = sms.sent_at
        order_sms.order = sms.order
        order_sms.polymorphic_ctype = ContentType.objects.get_for_model(OrderSMSMessage, for_concrete_model=False)
        order_sms.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0108_auto_20180706_0024'),
    ]

    operations = [
        # migrations.RunPython(code=migrations.RunPython.noop, reverse_code=reverse_delete_migration),
        # migrations.RemoveField(
        #     model_name='ordersmsmessage',
        #     name='order',
        # ),
        # migrations.DeleteModel(
        #     name='OrderSMSMessage',
        # )
    ]
