# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-05 07:06
from __future__ import unicode_literals

from django.db import migrations, models


def fill_raw_address(apps, schema):
    OrderLocation = apps.get_model('tasks', 'orderlocation')
    OrderLocation.objects.exclude(description='').update(raw_address=models.F('description'))


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0109_auto_20180706_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlocation',
            name='raw_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(fill_raw_address, migrations.RunPython.noop),
    ]
