# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 11:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0109_auto_20180706_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminatecode',
            name='email_notification_recipient',
            field=django.contrib.postgres.fields.citext.CIEmailField(blank=True, max_length=50),
        ),
    ]
