# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-02 14:31
from __future__ import unicode_literals

import django
import jsonfield
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0109_auto_20180503_0004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExternalJob',
            new_name='OrderPrototype',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='external_job',
            new_name='model_prototype',
        ),
        migrations.AddField(
            model_name='order',
            name='external_job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       related_name='order', to='tasks.ExternalJobs'),
        ),
        migrations.AlterField(
            model_name='orderprototype',
            name='content',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AddField(
            model_name='orderprototype',
            name='external_job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='order_prototype', to='tasks.ExternalJobs'),
        ),
        migrations.AlterField(
            model_name='orderprototype',
            name='external_id',
            field=models.CharField(max_length=250, null=True, blank=True)
        ),
        migrations.AlterField(
            model_name='orderprototype',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderprototype',
            name='source_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE,
                                    to='contenttypes.ContentType'),
        ),
    ]
