# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-30 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0109_auto_20180706_2258'),
        ('tasks', '0109_merge_20180827_2032'),
    ]

    operations = [
    ]
