# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-09 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0110_terminatecode_email_notification_recipient'),
        ('tasks', '0110_orderlocation_raw_address'),
    ]

    operations = [
    ]
