# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 16:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0112_auto_20180516_0033_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderprototype',
            name='ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='orderprototype',
            unique_together=set([]),
        ),
        # Removing moved to ExternalJob fields
        migrations.RemoveField(
            model_name='orderprototype',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='orderprototype',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='orderprototype',
            name='source_type',
        ),
    ]
