# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-09 07:32
from __future__ import unicode_literals

from django.db import migrations, models


def back_remove_duplications(apps, schema):
    OrderLocation = apps.get_model('tasks', 'OrderLocation')
    Order = apps.get_model('tasks', 'Order')
    Customer = apps.get_model('tasks', 'Customer')
    duplicated_locations = OrderLocation.objects.order_by('address', 'location').values('address', 'location')\
        .annotate(dup_count=models.Count('id')).filter(dup_count__gt=1)
    print('\n%s duplicated locations\n' % duplicated_locations.count())
    for location_values in duplicated_locations:
        locations = OrderLocation.objects.filter(address=location_values['address'],
                                                 location=location_values['location'])
        main_location = locations.first()
        Customer.objects.filter(last_address__in=locations).update(last_address=main_location)
        for field_name in ['pickup_address', 'deliver_address','starting_point', 'ending_point']:
            Order.objects.filter(**{'%s__in' % field_name: locations}).update(**{field_name: main_location})
        locations.exclude(id=main_location.id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0112_auto_20181109_1832'),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, reverse_code=back_remove_duplications),
    ]
