# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 14:33
from __future__ import unicode_literals

import django
from django.conf import settings
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0111_auto_20180503_0149_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkdelayedupload',
            name='encoding',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='bulkdelayedupload',
            name='errors_found',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulkdelayedupload',
            name='lines',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderprototype',
            name='errors',
            field=jsonfield.fields.JSONField(blank=True),
        ),
        migrations.AddField(
            model_name='orderprototype',
            name='used_serializer',
            field=models.CharField(choices=[('external', 'EXTERNAL'), ('csv', 'CSV')], default='csv', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='bulkdelayedupload',
            name='method',
            field=models.CharField(choices=[('web', 'WEB'), ('api', 'API'), ('external', 'External API'), ('no_info', 'No info')], default='no_info', max_length=10),
        ),
        migrations.AddField(
            model_name='bulkdelayedupload',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
