# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-09 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0111_merge_20181110_0138'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderlocation',
            unique_together=set([('location', 'address', 'raw_address')]),
        ),
    ]
