# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-08 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0111_auto_20181109_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='terminate_code',
        )
    ]
