# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0112_auto_20180516_0033_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkdelayedupload',
            name='type',
        ),
    ]
