# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-16 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0112_auto_20181109_1832_2'),
        ('tasks', '0112_auto_20181109_0017'),
    ]

    operations = [
    ]
