# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0108_auto_20180706_0024'),
        ('tasks', '0115_auto_20180712_0425'),
    ]

    operations = [
    ]
