# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import jsonfield.fields
import radaro_utils.files.utils
import radaro_utils.radaro_csv.meta


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0116_merge_20180712_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVOrdersFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to=radaro_utils.files.utils.delayed_task_upload)),
                ('lines', models.PositiveIntegerField(default=0)),
                ('encoding', models.CharField(blank=True, max_length=256)),
                ('columns', jsonfield.fields.JSONField(default=[])),
                ('original_file_name', models.CharField(blank=True, max_length=2048)),
                ('blank_lines', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=(radaro_utils.radaro_csv.meta.CSVMetadataMixin, models.Model),
        ),
        migrations.AddField(
            model_name='orderprototype',
            name='line',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bulkdelayedupload',
            name='status',
            field=django_fsm.FSMField(default='created', max_length=50),
        ),
        migrations.AddField(
            model_name='csvordersfile',
            name='bulk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='csv_file', to='tasks.BulkDelayedUpload'),
        ),
    ]
