# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0117_auto_20180712_2303_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkdelayedupload',
            name='created_at',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.RenameField(
            model_name='bulkdelayedupload',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AddField(
            model_name='bulkdelayedupload',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                           verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='orderprototype',
            name='bulk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prototypes',
                                    to='tasks.BulkDelayedUpload'),
        ),
        migrations.RemoveField(
            model_name='bulkdelayedupload',
            name='file',
        ),
        migrations.RemoveField(
            model_name='bulkdelayedupload',
            name='encoding',
        ),
        migrations.RemoveField(
            model_name='bulkdelayedupload',
            name='errors_found',
        ),
        migrations.RemoveField(
            model_name='bulkdelayedupload',
            name='instances',
        ),
        migrations.RemoveField(
            model_name='bulkdelayedupload',
            name='lines',
        ),
        migrations.RemoveField(
            model_name='bulkdelayedupload',
            name='original_file_name',
        ),
        migrations.RemoveField(
            model_name='bulkdelayedupload',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='bulkdelayedupload',
            name='saved',
        ),
        migrations.RemoveField(
            model_name='bulkdelayedupload',
            name='state_params',
        ),
        migrations.RemoveField(
            model_name='bulkdelayedupload',
            name='data',
        ),
    ]
