# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-25 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0108_auto_20180614_1834'),
        ('tasks', '0118_auto_20180713_0057'),
    ]

    operations = [
    ]
