# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-29 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0109_auto_20180706_2258'),
        ('tasks', '0119_merge_20180725_2251'),
    ]

    operations = [
    ]
