# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-16 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0113_merge_20181116_1959'),
        ('tasks', '0121_merge_20180830_2200'),
    ]

    operations = [
    ]
