# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-11 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0051_merge_20190206_0142'),
        ('tasks', '0122_merge_20181117_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='actual_device',
            field=models.ForeignKey(blank=True, help_text="Driver's device that have used for work with current order", null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification.Device'),
        ),
    ]
