# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-03 12:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0123_order_actual_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_interval',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, null=True),
        ),
    ]
