# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-21 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0123_order_actual_device'),
        ('tasks', '0123_order_customer_survey'),
    ]

    operations = [
    ]
