# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-16 12:48
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0123_order_actual_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='serialized_track',
            field=jsonfield.fields.JSONField(blank=True, default=list),
        ),
    ]
