# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-06 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0124_merge_20190521_2122'),
        ('tasks', '0124_auto_20190516_2248'),
    ]

    operations = [
    ]
