# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-11 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0125_merge_20190606_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_review_opt_in',
            field=models.BooleanField(default=False, verbose_name='Customer review opt-in'),
        ),
    ]
