# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-20 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0125_merge_20190606_1929'),
        ('tasks', '0124_order_delivery_range'),
    ]

    operations = [
    ]
