# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-11 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0126_merge_20190620_2214'),
        ('tasks', '0126_order_customer_review_opt_in'),
    ]

    operations = [
    ]
