# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0106_merge_20190521_2122'),
        ('tasks', '0126_merge_20190620_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='orders', to='merchant.Label'),
        ),
        migrations.AlterField(
            model_name='order',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchant.Label'),
        ),
    ]
