# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-19 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0127_merge_20190711_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[('not_assigned', 'Not assigned'), ('assigned', 'Assigned'), ('pickup', 'Pick up'),
                         ('in_progress', 'In progress'), ('way_back', 'Way back'), ('delivered', 'Completed'),
                         ('failed', 'Failed')],
                default='not_assigned',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='pick_up_distance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
