# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-07 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0127_merge_20190711_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_data', models.TextField()),
                ('symbology', models.CharField(blank=True, max_length=50, null=True)),
                ('scanned', models.BooleanField(default=False)),
                ('required', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='tasks.Order')),
            ],
        ),
    ]
