# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0128_auto_20190604_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='label',
        ),
    ]
