# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-29 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0130_merge_20190709_1542'),
        ('tasks', '0127_merge_20190711_1912'),
    ]

    operations = [
    ]
