# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-30 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0131_merge_20190829_1747'),
        ('tasks', '0128_auto_20190719_2309'),
    ]

    operations = [
    ]
