# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-12 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0132_merge_20190904_0000'),
        ('tasks', '0133_auto_20190831_0016'),
    ]

    operations = [
    ]
