# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-17 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0134_merge_20190912_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliver_address_2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
