# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-16 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0135_order_deliver_address_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='scanned_upon_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
