# Generated by Django 2.2.5 on 2020-01-29 09:49

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0135_order_deliver_address_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='thumb_confirmation_signature_100x100_field',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=base.utils.ThumbnailsUploadPath()),
        ),
        migrations.AddField(
            model_name='order',
            name='thumb_pre_confirmation_signature_100x100_field',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=base.utils.ThumbnailsUploadPath()),
        ),
        migrations.AddField(
            model_name='orderconfirmationphoto',
            name='thumb_image_100x100_field',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=base.utils.ThumbnailsUploadPath()),
        ),
        migrations.AddField(
            model_name='orderpreconfirmationphoto',
            name='thumb_image_100x100_field',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=base.utils.ThumbnailsUploadPath()),
        ),
    ]
