# Generated by Django 2.2.5 on 2020-03-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0136_barcode_re_scanned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barcode',
            old_name='scanned',
            new_name='scanned_at_the_warehouse',
        ),
    ]
