# Generated by Django 2.2.5 on 2020-02-03 14:03

from django.db import migrations
from jsonfield import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0136_auto_20200121_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Order',
            old_name='path',
            new_name='old_path'
        ),
        migrations.RenameField(
            model_name='Order',
            old_name='real_path',
            new_name='old_real_path'
        ),
        migrations.AddField(
            model_name='Order',
            name='path',
            field=JSONField(blank=True, null=True)
        ),
        migrations.AddField(
            model_name='Order',
            name='real_path',
            field=JSONField(blank=True, null=True)
        ),
    ]
