# Generated by Django 2.2.5 on 2020-03-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0137_auto_20200306_2251'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('deleted', False), ('status__in', ['in_progress', 'pickup', 'way_back', 'assigned'])), fields=['deleted', 'status'], name='tasks_order_index_sort_status'),
        ),
    ]
