# Generated by Django 2.2.5 on 2020-02-11 11:15

from django.db import migrations
from jsonfield import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0137_auto_20200204_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='picked_up_at',
        )
    ]
