# Generated by Django 2.2.5 on 2020-03-13 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0136_auto_20200225_0052'),
        ('tasks', '0137_auto_20200306_2251'),
    ]

    operations = [
    ]
