# Generated by Django 2.2.5 on 2020-04-07 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0137_auto_20200306_2251'),
        ('tasks', '0136_auto_20200129_2049'),
    ]

    operations = [
    ]
