# Generated by Django 2.2.5 on 2020-03-04 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0136_auto_20200225_0052'),
        ('tasks', '0138_auto_20200211_2215'),
    ]

    operations = [
    ]
