# Generated by Django 2.2.5 on 2020-02-13 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0138_auto_20200211_2215'),
        ('tasks', '0136_barcode_re_scanned'),
    ]

    operations = [
    ]
