# Generated by Django 2.2.5 on 2020-03-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0139_merge_20200305_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_before',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
