# Generated by Django 2.2.5 on 2020-03-04 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0136_auto_20200225_0052'),
        ('tasks', '0139_merge_20200213_2313'),
    ]

    operations = [
    ]
