# Generated by Django 2.2.5 on 2020-03-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0140_auto_20200305_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_geofence_entered',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='order',
            name='time_at_pickup',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='time_inside_pickup_geofence',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
