# Generated by Django 2.2.5 on 2020-03-06 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0140_auto_20200305_0013'),
        ('tasks', '0140_merge_20200304_2145'),
    ]

    operations = [
    ]
