# Generated by Django 2.2.5 on 2020-03-09 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0137_auto_20200306_2251'),
        ('tasks', '0141_merge_20200307_0047'),
    ]

    operations = [
    ]
