# Generated by Django 2.2.5 on 2020-03-13 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0137_auto_20200306_2251'),
        ('tasks', '0141_auto_20200312_2027'),
    ]

    operations = [
    ]
