# Generated by Django 2.2.5 on 2020-03-27 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0138_merge_20200327_1821'),
        ('tasks', '0142_merge_20200313_2007'),
    ]

    operations = [
    ]
