# Generated by Django 2.2.5 on 2020-03-13 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0142_merge_20200313_2007'),
        ('tasks', '0142_merge_20200310_0132'),
    ]

    operations = [
    ]
