# Generated by Django 2.2.5 on 2020-03-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0138_merge_20200313_1850'),
        ('tasks', '0143_merge_20200313_2329'),
    ]

    operations = [
    ]
