# Generated by Django 2.2.5 on 2020-03-30 07:18

from django.db import migrations, models
import django.db.models.deletion
import radaro_utils.radaro_phone.models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0124_merge_20200313_2007'),
        ('tasks', '0143_merge_20200328_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('phone', radaro_utils.radaro_phone.models.PhoneField(blank=True, max_length=128)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='merchant.Merchant')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='pickup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='tasks.Pickup'),
        ),
    ]
