# Generated by Django 2.2.5 on 2020-06-22 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0144_pickup'),
        ('tasks', '0138_orderlocation_address_2'),
    ]

    operations = [
    ]
