# Generated by Django 2.2.5 on 2020-04-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0144_merge_20200326_2055'),
        ('tasks', '0144_pickup'),
    ]

    operations = [
    ]
