# Generated by Django 2.2.5 on 2020-06-22 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0145_merge_20200402_2157'),
        ('tasks', '0145_merge_20200622_1819'),
    ]

    operations = [
    ]
