# Generated by Django 2.2.5 on 2020-06-25 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0146_merge_20200622_1836'),
        ('tasks', '0138_auto_20200313_0210'),
    ]

    operations = [
    ]
