# Generated by Django 2.2.5 on 2020-06-30 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0146_remove_order_deliver_address_2'),
    ]

    operations = [
        migrations.RunSQL(
            "WITH subquery AS (select id, "
            "CASE WHEN cardinality(old_path) > 0 THEN '{\"full\":[\"' || array_to_string(old_path, '\",\"') || '\"]}' "
            "WHEN cardinality(old_path) = 0 THEN '{\"full\": []}' "
            "END "
            "as new_path from tasks_order where old_path is not null)"
            "UPDATE tasks_order SET path = subquery.new_path FROM subquery WHERE tasks_order.id = subquery.id;",
            reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(
            "WITH subquery AS (select id, "
            "CASE WHEN cardinality(old_real_path) > 0 THEN '{\"full\":[\"' || array_to_string(old_real_path, '\",\"') || '\"]}' "
            "WHEN cardinality(old_real_path) = 0 THEN '{\"full\": []}' "
            "END "
            "as new_real_path from tasks_order where old_real_path is not null)"
            "UPDATE tasks_order SET real_path = subquery.new_real_path FROM subquery WHERE tasks_order.id = subquery.id;",
            reverse_sql=migrations.RunSQL.noop),
    ]
