# Generated by Django 2.2.5 on 2020-06-30 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0147_auto_20200630_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Order',
            name='old_path'
        ),
        migrations.RemoveField(
            model_name='Order',
            name='old_real_path'
        ),
    ]
