# Generated by Django 2.2.5 on 2020-07-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0148_auto_20200630_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkdelayedupload',
            name='uploaded_from',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
