# Generated by Django 2.2.5 on 2020-07-06 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0148_auto_20200630_2017'),
        ('tasks', '0147_merge_20200625_1637'),
    ]

    operations = [
    ]
