# Generated by Django 2.2.5 on 2020-07-09 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0148_auto_20200630_2017'),
        ('tasks', '0138_merge_20200407_1715'),
    ]

    operations = [
    ]
