# Generated by Django 2.2.5 on 2020-07-21 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0149_order_capacity'),
        ('tasks', '0149_merge_20200707_0049'),
    ]

    operations = [
    ]
