# Generated by Django 2.2.5 on 2020-08-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0149_skid'),
    ]

    operations = [
        migrations.AddField(
            model_name='skid',
            name='sizes_unit',
            field=models.CharField(choices=[('cm', 'Centimeters'), ('in', 'Inches')], default='cm', max_length=10),
        ),
        migrations.AddField(
            model_name='skid',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lb', 'Pounds')], default='kg', max_length=10),
        ),
    ]
