# Generated by Django 2.2.5 on 2020-08-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0149_order_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Integer capacity value in local units of measurement', null=True),
        ),
    ]
