# Generated by Django 2.2.5 on 2020-07-09 13:58

import base.utils.path_generators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0149_merge_20200709_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpickupconfirmationphoto',
            name='thumb_image_100x100_field',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=base.utils.path_generators.ThumbnailsUploadPath()),
        ),
    ]
