# Generated by Django 2.2.5 on 2020-07-14 09:34

import base.utils.path_generators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0150_orderpickupconfirmationphoto_thumb_image_100x100_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='thumb_pick_up_confirmation_signature_100x100_field',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=base.utils.path_generators.ThumbnailsUploadPath()),
        ),
    ]
