# Generated by Django 2.2.5 on 2020-07-23 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0149_bulkdelayedupload_uploaded_from'),
        ('tasks', '0150_merge_20200722_0156'),
    ]

    operations = [
    ]
