# Generated by Django 2.2.5 on 2020-07-27 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0151_merge_20200723_1941'),
        ('tasks', '0149_remove_barcode_symbology'),
    ]

    operations = [
    ]
