# Generated by Django 2.2.5 on 2020-09-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0151_auto_20200908_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skid',
            options={'ordering': ['id']},
        ),
    ]
