# Generated by Django 2.2.5 on 2020-09-18 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0152_auto_20200910_2002'),
        ('tasks', '0150_auto_20200808_0000'),
    ]

    operations = [
    ]
