# Generated by Django 2.2.5 on 2020-10-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0152_auto_20200910_2002'),
        ('tasks', '0151_order_thumb_pick_up_confirmation_signature_100x100_field'),
    ]

    operations = [
    ]
