# Generated by Django 2.2.5 on 2020-08-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0152_merge_20200727_2249'),
        ('tasks', '0149_skid'),
    ]

    operations = [
    ]
