# Generated by Django 2.2.5 on 2020-08-18 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0150_auto_20200807_0035'),
        ('tasks', '0153_merge_20200806_0002'),
    ]

    operations = [
    ]
