# Generated by Django 2.2.5 on 2021-02-05 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0153_merge_20200918_1951'),
        ('tasks', '0149_bulkdelayedupload_uploaded_from'),
    ]

    operations = [
    ]
