# Generated by Django 2.2.5 on 2020-11-26 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0153_merge_20200918_1951'),
        ('tasks', '0153_merge_20201027_2205'),
    ]

    operations = [
    ]
