# Generated by Django 2.2.5 on 2021-02-25 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0154_merge_20201126_2030'),
        ('tasks', '0154_merge_20210205_2156'),
    ]

    operations = [
    ]
