# Generated by Django 2.2.5 on 2021-08-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0154_merge_20210205_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='enable_rating_reminder',
            field=models.BooleanField(default=True),
        ),
    ]
