# Generated by Django 2.2.5 on 2020-08-18 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0150_auto_20200808_0000'),
        ('tasks', '0154_merge_20200818_1643'),
    ]

    operations = [
    ]
