# Generated by Django 2.2.5 on 2020-09-14 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0152_auto_20200910_2002'),
        ('tasks', '0155_merge_20200818_1917'),
    ]

    operations = [
    ]
