# Generated by Django 2.2.5 on 2021-05-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0155_auto_20210515_2253'),
        ('tasks', '0155_merge_20210225_2333'),
    ]

    operations = [
    ]
