# Generated by Django 2.2.5 on 2020-11-10 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0156_merge_20200914_2043'),
        ('tasks', '0153_merge_20201027_2205'),
    ]

    operations = [
    ]
