# Generated by Django 2.2.5 on 2021-06-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0156_merge_20210519_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
