# Generated by Django 2.2.5 on 2020-11-24 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0157_merge_20201110_1709'),
        ('tasks', '0153_merge_20200918_1951'),
    ]

    operations = [
    ]
