# Generated by Django 2.2.5 on 2021-09-02 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0155_order_enable_rating_reminder'),
        ('tasks', '0157_barcode_comment'),
    ]

    operations = [
    ]
