# Generated by Django 2.2.5 on 2021-08-23 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0157_barcode_comment'),
        ('tasks', '0155_order_enable_rating_reminder'),
    ]

    operations = [
    ]
