# Generated by Django 2.2.5 on 2021-10-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0158_merge_20210902_1727'),
        ('tasks', '0158_merge_20210823_2054'),
    ]

    operations = [
    ]
