# Generated by Django 2.2.5 on 2020-11-26 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0154_merge_20201126_2030'),
        ('tasks', '0158_merge_20201124_2301'),
    ]

    operations = [
    ]
