# Generated by Django 2.2.5 on 2021-02-05 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0154_merge_20210205_2156'),
        ('tasks', '0159_merge_20201127_0004'),
    ]

    operations = [
    ]
