# Generated by Django 2.2.5 on 2021-10-27 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0159_merge_20211014_2051'),
        ('tasks', '0158_merge_20211022_0621'),
    ]

    operations = [
    ]
