# Generated by Django 2.2.5 on 2021-02-25 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0160_merge_20210206_0138'),
        ('tasks', '0155_merge_20210225_2333'),
    ]

    operations = [
    ]
