# Generated by Django 2.2.5 on 2022-01-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0160_merge_20211027_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
