# Generated by Django 2.2.5 on 2022-02-14 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0161_auto_20220126_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='capacity',
            field=models.FloatField(blank=True, help_text='Float capacity value in local units of measurement', null=True, validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
    ]
