# Generated by Django 2.2.5 on 2021-05-31 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0161_merge_20210226_0120'),
        ('tasks', '0156_merge_20210519_2303'),
    ]

    operations = [
    ]
