# Generated by Django 2.2.5 on 2021-07-05 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0157_barcode_comment'),
        ('tasks', '0162_merge_20210531_1750'),
    ]

    operations = [
    ]
