# Generated by Django 2.2.5 on 2022-04-20 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0149_remove_barcode_symbology'),
        ('tasks', '0162_auto_20220214_2031'),
    ]

    operations = [
    ]
