# Generated by Django 2.2.5 on 2021-08-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0155_order_enable_rating_reminder'),
        ('tasks', '0163_merge_20210705_2229'),
    ]

    operations = [
    ]
