# Generated by Django 2.2.5 on 2021-09-03 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0164_merge_20210817_2106'),
        ('tasks', '0158_merge_20210902_1727'),
    ]

    operations = [
    ]
