# Generated by Django 2.2.5 on 2021-10-24 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0158_merge_20211022_0621'),
        ('tasks', '0165_merge_20210903_2259'),
    ]

    operations = [
    ]
