# Generated by Django 2.2.5 on 2021-11-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0166_merge_20211025_0224'),
        ('tasks', '0160_merge_20211027_2048'),
    ]

    operations = [
    ]
