# Generated by Django 2.2.5 on 2022-01-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0161_auto_20220126_2334'),
        ('tasks', '0167_merge_20211103_2333'),
    ]

    operations = [
    ]
