# Generated by Django 2.2.5 on 2022-03-25 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0162_auto_20220214_2031'),
        ('tasks', '0168_merge_20220127_0112'),
    ]

    operations = [
    ]
