# Generated by Django 2.2.5 on 2022-04-22 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0169_merge_20220325_2243'),
        ('tasks', '0163_merge_20220420_2355'),
    ]

    operations = [
    ]
