# Generated by Django 2.2.5 on 2022-05-27 11:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0164_auto_20220527_2000'),
        ('tasks', '0170_merge_20220422_1843'),
    ]

    operations = [
    ]
