# Generated by Django 2.2.5 on 2022-07-11 13:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0171_merge_20220527_2106'),
        ('tasks', '0165_order_store_url'),
    ]

    operations = [
    ]
