# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-27 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revelsystem',
            name='last_update',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
