# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-16 08:05
from __future__ import unicode_literals
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_revelsystem_last_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revelsystem',
            old_name='name',
            new_name='subdomain'
        ),
        migrations.AlterField(
            model_name='revelsystem',
            name='subdomain',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('[\\w-]+')]),
        ),
        migrations.AlterField(
            model_name='revelsystem',
            name='last_update',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
