# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-17 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_auto_20161116_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='revelsystem',
            name='importing',
            field=models.BooleanField(default=False),
        ),
    ]
