# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(blank=True, max_length=50, null=True)),
                ('car_type', models.IntegerField(choices=[(0, 'Bicycle'), (1, 'Bike'), (2, 'Car'), (3, 'Minibus'), (4, 'Truck')])),
                ('capacity_kg', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'member'},
        ),
        migrations.RemoveField(
            model_name='member',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='member',
            name='role',
        ),
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='member',
            name='car',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Car'),
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(default='VW'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
