# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 12:33
from __future__ import unicode_literals

import base.models
from django.db import migrations, models

import radaro_utils.files.utils


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20160128_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=radaro_utils.files.utils.get_upload_path),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=radaro_utils.files.utils.get_upload_path),
        ),
    ]
