# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 16:36
from __future__ import unicode_literals

from django.core.management import call_command
import os

from django.core import serializers
from django.db import migrations


fixture_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../fixtures'))
fixture_filename = 'groups.json'


def load_fixture(apps, schema_editor):
    fixture_file = os.path.join(fixture_dir, fixture_filename)
    call_command("loaddata", fixture_file)


def unload_fixture(apps, schema_editor):
    MyModel = apps.get_model("auth", "Group")
    MyModel.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20160129_1233')
    ]

    operations = [
        migrations.RunPython(load_fixture, unload_fixture)
    ]

