# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 08:07
from __future__ import unicode_literals

import base.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
        ('base', '0004_auto_20160129_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('pickup_from', models.DateTimeField(default=datetime.datetime(2016, 2, 1, 8, 7, 40, 531208, tzinfo=utc))),
                ('pickup_before', models.DateTimeField()),
                ('deliver_from', models.DateTimeField(default=datetime.datetime(2016, 2, 1, 8, 7, 40, 531275, tzinfo=utc))),
                ('deliver_before', models.DateTimeField()),
                ('status', models.CharField(blank=True, choices=[(-2, 'Failed'), (-1, 'Rejected'), (0, 'Created'), (1, 'Assigned'), (2, 'In progress'), (3, 'Delivered'), (4, 'Confirmed')], max_length=20, null=True)),
                ('deliver_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliver', to='routing.Location')),
            ],
        ),
        migrations.AlterModelManagers(
            name='member',
            managers=[
                ('objects', models.Manager()),
                ('drivers', base.models.DriversManager()),
                ('managers', base.models.ManagersManager()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Merchant'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup', to='routing.Location'),
        ),
    ]
