# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20160201_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliver_from',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_from',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
