# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0002_auto_20160203_1520'),
        ('base', '0008_member_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deliver_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='order',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_address',
        ),
        migrations.AddField(
            model_name='member',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routing.Location'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
