# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20160205_0833'),
        ('routing', '0002_auto_20160203_1520'),
        ('base', '0010_auto_20160204_1454'),
        ('merchant', '0002_auto_20160205_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='location',
        ),
        migrations.RemoveField(
            model_name='member',
            name='location',
        ),
        migrations.AddField(
            model_name='member',
            name='location',
            field=models.ManyToManyField(to='routing.Location', null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='merchant.Merchant'),
        ),
        migrations.DeleteModel(
            name='Merchant',
        ),
    ]
