# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20160205_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_ping',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
