# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_invite_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='pin_code_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
