# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_invite_pin_code_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='phone',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
