# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20160303_1434'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together=set([]),
        ),
    ]
