# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-09 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20160304_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='capacity_kg',
            field=models.PositiveIntegerField(default=1500),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.IntegerField(choices=[(0, 'Bicycle'), (1, 'Bike'), (2, 'Car'), (3, 'Minibus'), (4, 'Truck')], default=2),
        ),
    ]
