# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-09 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20160309_0924'),
    ]
    operations = [
        migrations.RemoveField(
            model_name='member',
            name='location',
        ),
    ]

