# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-18 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_member_thumb_avatar_100x100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='thumb_avatar_100x100',
        ),
    ]
