# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-24 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20160516_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.IntegerField(choices=[(2, 'Ute'), (0, 'Scooter'), (1, 'Car'), (3, 'Van'), (4, 'Truck')], default=1),
        ),
    ]
