# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-20 10:49
from __future__ import unicode_literals

import re

from django.db import migrations

from phonenumbers import parse, format_number, PhoneNumberFormat


def change_phone_format(apps, schema_editor):
    Member = apps.get_model('base', 'Member')
    members = Member.objects.filter(merchant__isnull=False)
    for member in members:
        try:
            phone = parse(member.phone, member.merchant.country)
            international_phone = format_number(phone, PhoneNumberFormat.INTERNATIONAL)
            member.phone = re.sub(r'[\s-]', '', international_phone)
            if not Member.objects.filter(phone=member.phone).exists():
                member.save()
        except Exception:
            pass


def change_invitation_phone(apps, schema_editor):
    Invite = apps.get_model('base', 'Invite')
    invitations = Invite.objects.all()
    for invite in invitations:

        try:
            phone = parse(invite.phone, invite.merchant.country)
            international_phone = format_number(phone, PhoneNumberFormat.INTERNATIONAL)
            invite.phone = re.sub(r'[\s-]', '', international_phone)
            if not Invite.objects.filter(phone=invite.phone).exists():
                invite.save()
        except Exception as exc:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20160516_1826'),
        ('merchant', '0015_merchant_country'),
    ]

    operations = [
        migrations.RunPython(change_phone_format, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(change_invitation_phone, reverse_code=migrations.RunPython.noop),
    ]
