# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-24 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20160524_2152'),
        ('base', '0025_auto_20160520_2049'),
    ]

    operations = [
    ]
