# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-24 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.IntegerField(choices=[(0, 'Scooter'), (1, 'Car'), (2, 'Pickup / Ute'), (3, 'Van'), (4, 'Truck')], default=1),
        ),
    ]
