# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-18 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20160525_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='position',
            field=models.PositiveIntegerField(choices=[(16, 'Admin Manager'), (8, 'Manager'), (1, 'Driver'), (0, 'OUT_OF_ROLE')], default=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.PositiveIntegerField(choices=[(16, 'Admin Manager'), (8, 'Manager'), (1, 'Driver'), (0, 'OUT_OF_ROLE')], default=0),
        ),
    ]
