# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-03 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_auto_20160718_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutablemodelparameters',
            name='message',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
