# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-03 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20160803_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutablemodelparameters',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mutablemodelparameters',
            name='name',
            field=models.CharField(editable=False, max_length=256, unique=True),
        ),
    ]
