# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-08 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_auto_20160803_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_offline_forced',
            field=models.BooleanField(default=False),
        ),
    ]
