# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-30 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_samplefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplefile',
            name='category',
            field=models.CharField(choices=[('csv_import', 'CSV Import Example')], max_length=256, unique=True),
        ),
    ]
