# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-07 07:10
from __future__ import unicode_literals

from django.db import migrations, models

import base.utils


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_auto_20160830_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplefile',
            name='file',
            field=models.FileField(upload_to=base.utils.get_custom_upload_path),
        ),
    ]
