# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 15:25
from __future__ import unicode_literals

from django.db import migrations


def member_id_migration(apps, schema_editor):
    Member = apps.get_model('base', 'Member')
    for m in Member.objects.all():
        m.member_id = m.id
        m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_member_driver_id'),
    ]

    operations = [
        migrations.RunPython(code=member_id_migration)
    ]
