# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_auto_20161125_0225'),
        ('merchant', '0034_auto_20161123_1935')
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.PositiveIntegerField(db_index=True, unique=True),
        ),
    ]
