# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 09:40
from __future__ import unicode_literals

import json

from django.db import migrations


def values_migration(apps, schema_editor):
    MutableModelParameters = apps.get_model('base', 'MutableModelParameters')
    defaults = {
        'DEFAULT_SMS_COST': {'constraints': {'min': 0}, 'type': 'float'},
        'DEFAULT_JOB_COST': {'constraints': {'min': 0}, 'type': 'float'},
        'EVENT_UPDATING_ALLOWED': {'constraints': {}, 'type': 'bool'},
        'TOKEN_TIMEOUT_MIN': {'constraints': {'min': 0}, 'type': 'int'},
        'INVITE_PIN_LENGTH': {'constraints': {'min': 4, 'max': 10}, 'type': 'int'}
    }
    values = []
    for param in MutableModelParameters.objects.all():
        dump = {'value': param.value, 'message': param.message, 'name': param.name}
        dump.update(defaults[param.name])
        if dump['name'] == 'EVENT_UPDATING_ALLOWED':
            dump['value'] = 'True'
            dump['message'] = 'Enables or disables receiving update events on clients.'
        values.append(dump)
    with open('values.json', 'wt') as f:
        f.write(json.dumps(values))
    MutableModelParameters.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_auto_20161125_0235'),
    ]

    operations = [
        migrations.RunPython(code=values_migration, reverse_code=migrations.RunPython.noop)
    ]
