# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_auto_20161207_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutablemodelparameters',
            name='constraints',
            field=jsonfield.fields.JSONField(default={}, editable=False),
        ),
        migrations.AddField(
            model_name='mutablemodelparameters',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mutablemodelparameters',
            name='type',
            field=models.CharField(
                choices=[('int', 'Integer'), ('float', 'Float'), ('bool', 'Boolean'), ('str', 'String')], default='int',
                max_length=8),
        ),
        migrations.AlterField(
            model_name='mutablemodelparameters',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        )
    ]
