# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_driverlocation_point_type'),
        ('base', '0041_auto_20161207_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_driver', to='driver.DriverLocation'),
        )
    ]
