# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    def fill_last_locations(apps, schema_editor):
        MANAGER = 16
        DRIVER = 1
        MANAGER_OR_DRIVER = MANAGER | DRIVER

        Member = apps.get_model('base', 'Member')
        for d in Member.objects.filter(role__in=[DRIVER, MANAGER_OR_DRIVER], is_active=True):
            d.last_location = d.location.order_by('timestamp').last()
            d.save()

    dependencies = [
        ('base', '0042_auto_20170117_1916'),
    ]

    operations = [
        migrations.RunPython(fill_last_locations, reverse_code=migrations.RunPython.noop)
    ]
