# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-07 12:09
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_auto_20170407_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='current_path',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
