# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-10 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_member_current_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='car',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Car'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_driver', to='driver.DriverLocation'),
        ),
        migrations.AlterField(
            model_name='member',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='merchant.Merchant'),
        ),
    ]
