# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-07 10:24
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_auto_20170421_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='serialized_track',
            field=jsonfield.fields.JSONField(default=[]),
        ),
    ]
