# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-03 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0055_merchant_use_way_back_status'),
        ('base', '0047_auto_20170421_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchant.Hub'),
        ),
    ]
