# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-26 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_auto_20170421_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MutableModelParameters',
        ),
        migrations.AlterField(
            model_name='invite',
            name='pin_code',
            field=models.CharField(blank=True, db_index=True, max_length=4),
        ),
    ]
