# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-05 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_remove_member_serialized_track'),
        ('base', '0049_auto_20170701_0002'),
        ('base', '0048_member_current_path_updated'),
    ]

    operations = [
    ]
