# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-20 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_car_hub'),
        ('base', '0050_merge_20170905_1941'),
    ]

    operations = [
    ]
