# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-13 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_merge_20170920_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=40),
        ),
    ]
