# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 14:13
from __future__ import unicode_literals

import base.models.members
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_merge_20170920_2234'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='member',
            managers=[
                ('objects', models.Manager()),
                ('drivers', base.models.members.ActiveDriversManager()),
                ('drivers_with_statuses', base.models.members.ActiveDriversManagerWithStatuses()),
                ('all_drivers', base.models.members.DriversManager()),
                ('managers', base.models.members.ManagersManager()),
            ],
        ),
    ]
