# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-12 10:49
from __future__ import unicode_literals

from django.db import migrations, models


def confirmation_email_sent_set_true(apps, schema_editor):
    Member = apps.get_model('base', 'Member')
    Member.objects.all().update(confirmation_email_sent=True)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_merge_20170920_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='confirmation_email_sent',
            field=models.BooleanField(default=False, help_text='Designates whether the confirmation email was sent.'),
        ),
        migrations.RunPython(confirmation_email_sent_set_true, reverse_code=migrations.RunPython.noop)
    ]
