# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_auto_20180314_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='phone',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
