# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_auto_20180314_2153'),
        ('base', '0052_member_confirmation_email_sent'),
    ]

    operations = [
    ]
