# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_auto_20180321_0113'),
        ('base', '0054_merge_20180402_2346'),
    ]

    operations = [
    ]
