# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-10 09:07
from __future__ import unicode_literals

import django
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_merge_20180403_1817'),
    ]

    operations = [
        CITextExtension(),
        migrations.AlterField(
            model_name='invite',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(max_length=254, unique=True,
                                                                     verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=django.contrib.postgres.fields.citext.CICharField(
                error_messages={'unique': 'A user with that username already exists.'},
                help_text='Required. 256 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=256,
                unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$',
                                                                               'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')],
                verbose_name='username'),
        ),
    ]
