# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-18 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_auto_20180410_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='position',
            field=models.PositiveIntegerField(choices=[(16, 'Admin Manager'), (8, 'Manager'), (1, 'Driver'), (2, 'Observer'), (0, 'OUT_OF_ROLE')], default=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.PositiveIntegerField(choices=[(16, 'Admin Manager'), (8, 'Manager'), (1, 'Driver'), (2, 'Observer'), (0, 'OUT_OF_ROLE')], default=0),
        ),
    ]
