# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 12:22
from __future__ import unicode_literals

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_auto_20180518_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='thumb_avatar_100x100_field',
            field=models.ImageField(blank=True, null=True, upload_to=base.utils.ThumbnailsUploadPath()),
        ),
    ]
