# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-01 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_auto_20180518_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='expected_driver_route',
            field=models.TextField(blank=True, null=True),
        ),
    ]
