# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-24 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_auto_20180817_0011'),
        ('base', '0058_member_expected_driver_route'),
    ]

    operations = [
    ]
