# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-27 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_auto_20180817_0011'),
        ('base', '0058_auto_20180614_1834'),
    ]

    operations = [
    ]
