# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_merge_20180827_2031'),
        ('base', '0060_merge_20180822_0405'),
    ]

    operations = [
    ]
