# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-15 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_merge_20180824_2040'),
        ('base', '0061_merge_20180830_2200'),
    ]

    operations = [
    ]
