# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-30 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0106_auto_20190531_0005'),
        ('base', '0062_merge_20181015_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='skill_sets',
            field=models.ManyToManyField(blank=True, related_name='drivers', to='merchant.SkillSet'),
        ),
    ]
