# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-06 07:45
from __future__ import unicode_literals

from django.db import migrations
from django.template.loader import get_template

from notification.mixins import MessageTemplateStatus


def change_complete_invitation_default_template(apps, schema_editor):
    MerchantMessageTemplate = apps.get_model('notification', 'MerchantMessageTemplate')
    templates = MerchantMessageTemplate.objects.filter(template_type=MessageTemplateStatus.COMPLETE_INVITATION)

    template_name = MessageTemplateStatus.template_names_map.get(MessageTemplateStatus.COMPLETE_INVITATION)
    text = get_template(template_name + '.txt').template.source

    templates.update(text=text)


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0063_member_skill_sets'),
    ]

    operations = [
        migrations.RunPython(code=change_complete_invitation_default_template, reverse_code=migrations.RunPython.noop)
    ]
