# Generated by Django 2.2.5 on 2020-01-29 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_auto_20191106_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='sub_branding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='merchant.SubBranding'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='position',
            field=models.PositiveIntegerField(choices=[(16, 'Admin Manager'), (8, 'Manager'), (4, 'Sub brand manager'), (1, 'Driver'), (2, 'Observer'), (0, 'OUT_OF_ROLE')], default=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.PositiveIntegerField(choices=[(16, 'Admin Manager'), (8, 'Manager'), (4, 'Sub brand manager'), (1, 'Driver'), (2, 'Observer'), (0, 'OUT_OF_ROLE')], default=0),
        ),
    ]
