# Generated by Django 2.2.5 on 2020-04-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_remove_member_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='has_internet_connection',
            field=models.BooleanField(default=False),
        ),
    ]
