# Generated by Django 2.2.5 on 2020-06-12 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0120_merchant_round_corners_for_customer'),
        ('base', '0068_member_internet_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='ending_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member_ending', to='merchant.Hub'),
        ),
        migrations.AddField(
            model_name='member',
            name='ending_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member_ending', to='merchant.HubLocation'),
        ),
        migrations.AddField(
            model_name='member',
            name='starting_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member_starting', to='merchant.Hub'),
        ),
        migrations.AddField(
            model_name='member',
            name='starting_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member_starting', to='merchant.HubLocation'),
        ),
    ]
