# Generated by Django 2.2.5 on 2020-07-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_auto_20200612_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='capacity_kg',
        ),
        migrations.AddField(
            model_name='car',
            name='capacity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
