# Generated by Django 2.2.5 on 2021-05-17 13:24

from django.db import migrations, models


OLD_ADMIN_ROLE, NEW_ADMIN_ROLE = 16, 32
OLD_MANAGER_ROLE, NEW_MANAGER_ROLE = 8, 16


def update_admin_roles(apps, schema_editor):
    member = apps.get_model('base', 'Member')
    member.objects.filter(role=OLD_ADMIN_ROLE).update(role=NEW_ADMIN_ROLE)
    member.objects.filter(role=OLD_MANAGER_ROLE).update(role=NEW_MANAGER_ROLE)


def revert_admin_roles(apps, schema_editor):
    member = apps.get_model('base', 'Member')
    member.objects.filter(role=NEW_MANAGER_ROLE).update(role=OLD_MANAGER_ROLE)
    member.objects.filter(role=NEW_ADMIN_ROLE).update(role=OLD_ADMIN_ROLE)


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0144_merge_20210505_1713'),
        ('base', '0072_auto_20200808_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='merchants',
            field=models.ManyToManyField(blank=True, related_name='group_managers', to='merchant.Merchant', verbose_name='Group manager merchants', help_text='Choose merchant accounts that will be available for the manager.'),
        ),
        migrations.AddField(
            model_name='member',
            name='sub_brandings',
            field=models.ManyToManyField(blank=True, related_name='group_managers', to='merchant.SubBranding', verbose_name='Group manager sub-brandings'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='position',
            field=models.PositiveIntegerField(choices=[(32, 'Admin Manager'), (16, 'Manager'), (8, 'Group manager'), (4, 'Sub brand manager'), (1, 'Driver'), (17, 'Manager / Driver'), (2, 'Observer'), (0, 'OUT_OF_ROLE')], default=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.PositiveIntegerField(choices=[(32, 'Admin Manager'), (16, 'Manager'), (8, 'Group manager'), (4, 'Sub brand manager'), (1, 'Driver'), (17, 'Manager / Driver'), (2, 'Observer'), (0, 'OUT_OF_ROLE')], default=0),
        ),
        migrations.RunPython(update_admin_roles, reverse_code=revert_admin_roles)
    ]
