# Generated by Django 2.2.5 on 2021-07-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0073_auto_20210517_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='show_only_sub_branding_jobs',
            field=models.BooleanField(default=False, help_text='Setting for Group Manager page. Show only sub-brandings jobs in case chosen merchant has jobs with and without sub-brandings.', verbose_name='Show only sub-brandings jobs'),
        ),
    ]
