# Generated by Django 2.2.5 on 2021-09-29 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0146_merchant_time_today_reminder'),
        ('base', '0074_member_show_only_sub_branding_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='merchant.Merchant'),
        ),
    ]
