# Generated by Django 2.2.5 on 2021-11-12 10:42

import base.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_member_show_only_sub_branding_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='one_time_capacities',
            field=base.fields.OneTimeValuesField(blank=True),
        ),
    ]
