# Generated by Django 2.2.5 on 2021-09-29 13:35

from django.db import migrations, models
import django.db.models.deletion


def add_merchant(apps, schema_editor):
    Merchant = apps.get_model('merchant', 'Merchant')
    Invite = apps.get_model('base', 'Invite')
    for merchant in Merchant.objects.all():
        Invite.objects.filter(initiator__merchant=merchant).update(merchant=merchant)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_invite_merchant'),
    ]

    operations = [
        migrations.RunPython(add_merchant, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='invite',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.Merchant'),
        ),
    ]
