# Generated by Django 2.2.5 on 2021-11-16 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import jsonfield.fields
import model_utils.fields
import radaro_utils.files.utils
import radaro_utils.radaro_csv.meta


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_car_one_time_capacities'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverScheduleUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', django_fsm.FSMField(default='created', max_length=50)),
                ('log', jsonfield.fields.JSONField(default=[])),
                ('method', models.CharField(choices=[('admin', 'admin'), ('web', 'WEB'), ('api', 'API'), ('external', 'External API'), ('no_info', 'No info')], default='no_info', max_length=10)),
                ('uploaded_from', models.CharField(blank=True, max_length=512)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CSVDriverSchedulesFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to=radaro_utils.files.utils.delayed_task_upload)),
                ('lines', models.PositiveIntegerField(default=0)),
                ('encoding', models.CharField(blank=True, max_length=256)),
                ('columns', jsonfield.fields.JSONField(default=[])),
                ('original_file_name', models.CharField(blank=True, max_length=2048)),
                ('blank_lines', models.PositiveIntegerField(default=0)),
                ('target_date', models.DateField()),
                ('bulk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='csv_file', to='base.DriverScheduleUpload')),
            ],
            options={
                'abstract': False,
            },
            bases=(radaro_utils.radaro_csv.meta.CSVMetadataMixin, models.Model),
        ),
    ]
