# Generated by Django 2.2.5 on 2021-09-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0076_auto_20210929_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='language',
            field=models.CharField(choices=[('en-au', 'English (Australia)'), ('en-gb', 'English (Great Britain)'), ('en-us', 'English (US)'), ('fr-ca', 'French (Canada)'), ('fr-be', 'French (Belgium)'), ('nl-be', 'Dutch (Belgium)'), ('nl-nl', 'Dutch (Netherlands)'), ('ko', 'Korean'), ('ja', 'Japanese')], default='en-au', help_text='Application language', max_length=10),
        ),
    ]
