# Generated by Django 2.2.5 on 2021-12-13 13:35

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0150_merge_20211014_2051'),
        ('base', '0076_csvdriverschedulesfile_driverscheduleupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverscheduleupload',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchant.Merchant'),
        ),
        migrations.AddField(
            model_name='driverscheduleupload',
            name='processed_data',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
