# Generated by Django 2.2.5 on 2021-11-22 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0076_csvdriverschedulesfile_driverscheduleupload'),
        ('base', '0076_auto_20210929_2335'),
    ]

    operations = [
    ]
