# Generated by Django 2.2.5 on 2021-12-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_member_language'),
        ('base', '0077_merge_20211125_2012'),
    ]

    operations = [
    ]
