# Generated by Django 2.2.5 on 2021-12-14 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_merge_20211123_0038'),
        ('base', '0077_member_language'),
    ]

    operations = [
    ]
