# Generated by Django 2.2.5 on 2021-12-15 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_auto_20211214_0035'),
        ('base', '0076_auto_20210929_2335'),
    ]

    operations = [
    ]
