# Generated by Django 2.2.5 on 2021-12-22 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0078_merge_20211215_0029'),
        ('base', '0077_merge_20211125_2012'),
    ]

    operations = [
    ]
