# Generated by Django 2.2.5 on 2022-01-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0078_merge_20211224_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplefile',
            name='category',
            field=models.CharField(choices=[('csv_import', 'CSV Import Example'), ('schedule_and_capacity_csv_import', 'Schedule and Capacity CSV Import Example')], max_length=256, unique=True),
        ),
    ]
