# Generated by Django 2.2.5 on 2022-02-11 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_auto_20220124_1757'),
        ('base', '0079_merge_20211223_2018'),
    ]

    operations = [
    ]
