# Generated by Django 2.2.5 on 2021-12-23 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_merge_20211223_0128'),
        ('base', '0079_merge_20211223_2018'),
    ]

    operations = [
    ]
