# Generated by Django 2.2.5 on 2021-12-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0078_merge_20211224_2042'),
        ('base', '0080_merge_20211223_2115'),
    ]

    operations = [
    ]
