# Generated by Django 2.2.5 on 2022-01-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0081_merge_20211224_2128'),
        ('base', '0079_auto_20220124_1757'),
    ]

    operations = [
    ]
