# Generated by Django 2.2.5 on 2022-03-22 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0081_auto_20220217_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='capacity',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
    ]
