# Generated by Django 2.2.5 on 2022-02-15 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0080_merge_20220211_2023'),
        ('base', '0082_merge_20220126_0016'),
    ]

    operations = [
    ]
