# Generated by Django 2.2.5 on 2022-07-26 07:06

import base.models.members
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0083_auto_20220629_2040'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='member',
            managers=[
                ('objects', base.models.members.MembersManager()),
                ('drivers', base.models.members.ActiveDriversManager()),
                ('drivers_with_statuses', base.models.members.ActiveDriversManagerWithStatuses()),
                ('all_drivers', base.models.members.DriversManager()),
                ('managers', base.models.members.ManagersManager()),
                ('all_objects', base.models.members.AllMembersManager()),
            ],
        ),
    ]
