# Generated by Django 2.2.5 on 2022-07-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_auto_20220712_0042'),
        ('base', '0083_auto_20220629_2040'),
    ]

    operations = [
    ]
