# Generated by Django 2.2.5 on 2022-02-18 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_merge_20220215_2032'),
        ('base', '0081_auto_20220217_2126'),
    ]

    operations = [
    ]
