# Generated by Django 2.2.5 on 2022-03-25 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0084_merge_20220218_2157'),
        ('base', '0082_auto_20220322_2043'),
    ]

    operations = [
    ]
