# Generated by Django 2.2.5 on 2022-06-30 13:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0085_merge_20220325_2243'),
        ('base', '0083_auto_20220629_2040'),
    ]

    operations = [
    ]
