# Generated by Django 2.2.5 on 2022-07-12 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0086_merge_20220630_2309'),
        ('base', '0083_auto_20220712_0042'),
    ]

    operations = [
    ]
