# Generated by Django 2.2.5 on 2022-07-27 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0087_merge_20220712_2020'),
        ('base', '0084_merge_20220726_1857'),
    ]

    operations = [
    ]
