# Generated by Django 2.2.5 on 2022-08-02 07:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0088_merge_20220727_2340'),
        ('base', '0084_auto_20220726_1706'),
    ]

    operations = [
    ]
