# server related variables list. all that is connected with deployment process

CURRENT_ENV = ''

HOST_IP = ''
KEY_FILENAME = ''

WORKON_DIR = 'venv'

NEW_RELIC_PROCESS_HOST_DISPLAY_NAME = ''

BALANCED_DOMAINS = []
SECURE_DOMAINS = []
INSECURE_DOMAINS = []

LETSENCRYPT_CERT_EMAIL = ''

USE_MONIT = False
MONIT_USE_AUTH = True
MONIT_PORT = ''
MONIT_LOGIN = ''
MONIT_PASSWORD = ''

MONIT_SLACK_NOTIFICATIONS = False
MONIT_SLACK_WEBHOOCK_URL = ''
MONIT_SLACK_CHANNEL = ''

LOCAL_REDIS_ENABLED = False

CELERYBEAT_ENABLED = False
CELERYD_DEFAULT_CONCURRENCY = 1
CELERYD_SLOW_CONCURRENCY = 2
CELERYD_PRIORITY_CONCURRENCY = 3

GUNI_PORT = 0
GUNI_WORKERS = 0

NGINX_CONF = ''
