"""
Django settings for delivery project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from copy import copy

# Celery
from .celery_configs import *

BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = r"pcl1=f_)3dr@(er&0ivba+d(-^!3j+0@2k^10z(0sn1_uzhl9d"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

ADMIN_SITE_SUPERADMINS = []

# Application definition

AUTH_USER_MODEL = 'base.Member'

INSTALLED_APPS = [
    'grappelli',
    'location_field',
    'delivery.apps.MyAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'adminplus',
    'corsheaders',
    'widget_tweaks',
    'rest_framework',
    'django_filters',
    'drf_secure_token',
    'timezone_field',
    'routing',
    'custom_auth',
    'base',
    'tasks',
    'driver',
    'merchant',
    'reporting',
    'documents',
    'watson',
    'pinax.stripe',
    'webhooks',
    'schedule',
    'notification',
    'push_notifications',
    'availability_monitor',
    'integrations',
    'testing',
    'django_markdown',
    'merchant_extension',
    'constance.backends.database',
    'constance',
    'daterange_filter',
    'logtailer',
    'crequest',
    'routing_optimization',
    'radaro_router',
    'radaro_utils.radaro_admin',
    'radaro_utils.radaro_csv',
    'radaro_utils.radaro_phone',
    'radaro_utils.radaro_model_utils',
    'radaro_utils.radaro_notifications',
    'anymail',
    'nested_admin',
    'route_optimisation',
    'djangosaml2',
]

MIDDLEWARE = [
    'radaro_utils.middlewares.middlewares.DisableClientCacheMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'radaro_utils.middlewares.LanguageMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'watson.middleware.SearchContextMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'drf_secure_token.middleware.UpdateTokenMiddleware',
    'crequest.middleware.CrequestMiddleware',
    'radaro_utils.middlewares.AdminPageRequestVersionMiddleware',
    'djangosaml2.middleware.SamlSessionMiddleware',
    'radaro_utils.middlewares.SetMerchantMiddleware',
    'radaro_utils.middlewares.CurrentRoleMiddleware'
]

ROOT_URLCONF = 'delivery.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'delivery.context_processors.google_analytics',
            ],
        },
    },
]

WSGI_APPLICATION = 'delivery.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'delivery',
        'USER': 'postgres',
        'PASSWORD': '',
        'HOST': 'localhost'
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'radaro_utils.password_validation.UpperCaseValidator',
    },
    {
        'NAME': 'radaro_utils.password_validation.LowerCaseValidator',
    },
    {
        'NAME': 'radaro_utils.password_validation.HasNumberValidator',
    },
]


AUTHENTICATION_BACKENDS = (
    'base.authentication.UserNameOrEmailBackend',
    'django.contrib.auth.backends.ModelBackend',
    'djangosaml2.backends.Saml2Backend',
)

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/
LANGUAGES = [
    ('en-au', 'English (Australia)'),
    ('en-gb', 'English (Great Britain)'),
    ('en-us', 'English (US)'),
    ('fr-ca', 'French (Canada)'),
    ('fr-be', 'French (Belgium)'),
    ('fr-fr', 'French (France)'),
    ('nl-be', 'Dutch (Belgium)'),
    ('nl-nl', 'Dutch (Netherlands)'),
    ('ko', 'Korean'),
    ('ja', 'Japanese'),
    ('pt-pt', 'Portuguese (Portugal)'),
    ('es', 'Spanish'),
]

# Language dialect, used as default for errors/messages/CMS
LANGUAGE_CODE = 'en-gb'

USER_DEFAULT_LANGUAGE_CODE = 'en-au'

TIME_ZONE = 'Australia/Melbourne'

USE_I18N = True

USE_L10N = True

USE_TZ = True

SITE_ID = 1


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'django.contrib.staticfiles.finders.FileSystemFinder',
)

FIXTURE_DIR = os.path.join(BASE_DIR, 'fixtures')

DATA_UPLOAD_MAX_MEMORY_SIZE = 3 * 1024 * 1024

# Rest framework
# http://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
        'rest_framework.permissions.IsAdminUser',
    ),
    'PAGE_SIZE': 10,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'custom_auth.authentication.I18NSecureTokenAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'base.utils.CustomPageNumberPagination',
    'EXCEPTION_HANDLER': 'base.utils.custom_exception_handler',
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
    'DEFAULT_VERSIONING_CLASS': 'radaro_utils.versioning.CustomURLPathVersioning',
    'DEFAULT_VERSION': 1,
    'VERSION_PARAM': 'api_version'
}

# Database connection life time
CONN_MAX_AGE = 60

# Token age setting
MUTABLE_PERIOD = 60 * 60 * 24 * 10  # 10 days
TOKEN_AGE = 60 * 60 * 24 * 30  # 30 days


APP_NAME = 'Delivery App'

DRIVER_INTERNET_CONNECTION_TIMEOUT = 2 * 60

CORS_ORIGIN_ALLOW_ALL = True

from corsheaders.defaults import default_headers

CORS_ALLOW_HEADERS = default_headers + ('x-return-language', 'X-Merchant', 'X-Role')

CORS_EXPOSE_HEADERS = ('X-Token', 'X-Return-Language', 'Content-Disposition', 'Redirect-Url', 'X-Merchant', 'X-Role')

MAX_ACCURACY_RANGE = 60.0

PROJECT_NAME = 'delivery'
DJANGO_LOG_NAME = 'django'

from radaro_utils import countries

CONSTANCE_ADDITIONAL_FIELDS = {
    'countries_select': ['merchant.forms.AllowedCountriesMultipleChoiceField', {
        'widget': 'django.forms.CheckboxSelectMultiple',
        'choices': countries.countries
    }],
    'mobile_app_version_field': ['base.forms.MobileAppVersionsField'],
    'emails_list': ['base.forms.CustomEmailArrayField', {
        'widget': 'base.forms.DynamicArrayWidget',
    }],
}

CONSTANCE_CONFIG = {
    'DISTANCE_THRESHOLD': (40.0, 'Distance in relation to previous coordinate to accept new coordinate.'
                                 '(Staging only for now. For testing purposes)'),
    'PATH_IMPROVING': (True, 'This parameter enables or disables advanced path processing.'),
    'NTI_TA_PHONE': ('1800 827 747', 'Phone number of the TA of NTI merchant.'),
    # TODO: remove 'NTI_MERCHANT_ID' after release Merchant.merchant_type feature
    'NTI_MERCHANT_ID': (24, 'ID of NTI merchant.'),
    'MASTER_PIN_ENABLED': (True, 'Possible value is "True" or "False". If value is "True"'
                                 'than "MASTER_PIN" setting will be enabled, else '
                                 '"MASTER_PIN" setting will be disabled.'),
    'MASTER_PIN': (6384, 'Setting defining default pin code for drivers registration. '
                         'Value should be an integer with number of digits equals to PIN length. '
                         'Illegal range or changing name leads to ignoring it and '
                         'creating new parameter with default random value.'),
    'DEFAULT_SMS_COST': (0.15, 'Default sms price to be applied to new merchants. Can be overwritten by personal '
                               '(for each merchant) price per sms done. Can be only numeric, larger or equal 0.'),
    'DEFAULT_JOB_COST': (0.55, 'Default job price to be applied to new merchants. Can be overwritten by personal '
                               '(for each merchant) price per job done. Can be only numeric, larger or equal 0.'),
    'DEFAULT_LOCATION_PROCESSING_COST': (0.0005, 'Default location processing price to be applied to new merchants. '
                                                 'Can be overwritten by personal (for each merchant). '
                                                 'Can be only numeric, larger or equal 0.'),
    'EVENT_UPDATING_ALLOWED': (True, 'Enables or disables receiving update events on clients.'),
    'TOKEN_TIMEOUT_MIN': (5, 'Setting defining timeout of pin code. Value in minutes. Illegal range or changing name '
                             'leads to ignoring it and creating new parameter with default value.'),
    'INVITE_PIN_LENGTH': (4, 'Settings defining length of invite pin code. Should be in range 4..10. Illegal range or '
                             'changing name leads to ignoring it and creating new parameter with default values.'),
    'IMPROVE_POINT_THRESHOLD_SPEED': (5.2, 'Point improving will be started if speed larger than this value. This '
                                           'can help in reducing loops on map when track driver.'),
    'CONFIRM_PHOTOS_UPLOAD_LIMIT': (5, 'Uploaded confirmation photos limit.'),
    'ALLOWED_COUNTRIES': (countries.DEFAULT_COUNTRIES, 'Select allowed countries', 'countries_select'),
    'ALLOWED_DELTA_IN_FUTURE': (5, 'Allows accept data with timestamps in future within set bounds (in seconds).'),
    'MAX_SMS_SENDER_LENGTH': (11, 'Max length value of sms sender name. If the value is greater than the max value sms '
                                  'will not send.'),
    'EMAILS_FOR_WEEKLY_REPORTS': ([], 'Emails for weekly Radaro usage reports', 'emails_list'),
    'MOBILE_APP_VERSIONS': ({}, 'Set matter versions of driver mobile apps', 'mobile_app_version_field'),
    'LABELS_LIMIT': (50, 'Merchant labels limit')
}
CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'
CONSTANCE_DATABASE_CACHE_BACKEND = 'default'

CONSTANCE_CONFIG_FIELDSETS = {
    'General config': (
        'ALLOWED_COUNTRIES', 'ALLOWED_DELTA_IN_FUTURE', 'CONFIRM_PHOTOS_UPLOAD_LIMIT', 'DEFAULT_JOB_COST',
        'DEFAULT_LOCATION_PROCESSING_COST', 'DEFAULT_SMS_COST', 'DISTANCE_THRESHOLD', 'EVENT_UPDATING_ALLOWED',
        'IMPROVE_POINT_THRESHOLD_SPEED', 'INVITE_PIN_LENGTH', 'MASTER_PIN', 'MASTER_PIN_ENABLED',
        'MAX_SMS_SENDER_LENGTH', 'NTI_MERCHANT_ID', 'NTI_TA_PHONE', 'PATH_IMPROVING', 'TOKEN_TIMEOUT_MIN',
        'MOBILE_APP_VERSIONS', 'EMAILS_FOR_WEEKLY_REPORTS', 'LABELS_LIMIT'
    )
}

TERMINATE_CODES = {
    'error': {
        'STARTING': 501,
        'OTHER': 550,
        'DEFAULT_CODES': (
            {'code': 501, 'name': 'Job Error #1'},
            {'code': 502, 'name': 'Job Error #2'},
            {'code': 503, 'name': 'Job Error #3'},
        )
    },
    'success': {
        'STARTING': 201,
        'OTHER': 250,
        'DEFAULT_CODES': (
            {'code': 201, 'name': 'Success #1'},
            {'code': 202, 'name': 'Success #2'},
            {'code': 203, 'name': 'Success #3'},
        )
    }
}

for code_type in TERMINATE_CODES:
    _codes = TERMINATE_CODES[code_type]
    _codes['MAX_COUNT'] = _codes['OTHER'] - _codes['STARTING'] + 1
    _codes['DEFAULT_CODES'] += ({'code': _codes['OTHER'], 'name': 'Other', 'is_comment_necessary': True}, )

# Markdown settings
MARKDOWN_EXTENSIONS = [
    'markdown.extensions.nl2br',
    'markdown.extensions.smarty',
    'markdown.extensions.tables',
    'markdown.extensions.attr_list',
    'markdown_extensions.urlize',
]

MARKDOWN_EXTENSION_CONFIGS = {
    'markdown.extensions.smarty': {
        'smart_angled_quotes': True
    }
}

MARKDOWN_PREVIEW_TEMPLATE = 'markdown/custom_preview.html'

LOCATION_FIELD = {
    'map.provider': 'google',
    'map.zoom': 8,

    'search.provider': 'google',
    'search.suffix': '',

    # Google
    'provider.google.api': '//maps.google.com/maps/api/js',
    'provider.google.api_key': '',
    'provider.google.map_type': 'ROADMAP',
}

INTERNAL_IPS = ('127.0.0.1', )

# Timeout for requests if services are down or smth. like this (in seconds)
SMS_SERVICE_TIMEOUT = 10
PUSH_SERVICE_TIMEOUT = 7
EXTERNAL_JOB_EVENT_TIMEOUT = 12
GOOGLE_API_TIMEOUT = 12

# After webhook url fails this amount of times in a row, notification will be sent.
WEBHOOK_FAIL_LIMIT = 500

PUSH_NOTIFICATIONS_SETTINGS = {
    "GCM_ERROR_TIMEOUT": PUSH_SERVICE_TIMEOUT,
    "FCM_ERROR_TIMEOUT": PUSH_SERVICE_TIMEOUT,
    "FCM_API_KEY": 'AAAAzTzRkG4:APA91bHXQWUkvfRbcSB41mGSrdhHCiI_IW7Eu5h5wWrkIJZxnrcwDPD066kQLCC7VgGSPsDdhkdwQmKP1qvYBm-dfQJsw4czY45SmDj3i085MOSeAugejf_go69iYU2IXODw7ZTljDSh',
    "GCM_API_KEY": "AIzaSyANufJukReCgAE4wxSAuVvSsRVJ_fcSzLs",
    "APNS_CERTIFICATE": os.path.join(BASE_DIR, 'radaroPushProd3.pem'),
    # "APNS_HOST": "gateway.sandbox.push.apple.com",
    "APNS_TOPIC": 'com.radaro',
    "CONFIG": "notification.configs.PushNotificationsConfig"
}

DEFAULT_DRIVER_ICON = 'default_driver_icon.png'

TESTING_MODE = sys.argv[1:2] == ['test']

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ.get('REDIS_DB', 'redis://127.0.0.1:6379/1'),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    "optimisation": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ.get('RO_REDIS_DB', 'redis://127.0.0.1:6379/1'),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    "test_optimisation": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "test_optimisation",
    },
}

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

CUSTOMER_MESSAGES = dict(
    task_period=10*60,  # 10 minutes
    reminder_timeout=5*60,  # twenty minutes
    follow_up_reminder_timeout=10*60,  # 24 hours
    upcoming_delivery_timeout=24*60*60,  # 24 hours
)


LATEST_API_VERSION = 2
MOBILE_API_VERSION = 3

DATA_UPLOAD_MAX_NUMBER_FIELDS = None


PTV_TOKEN = '634b5337-5bf3-40ad-98c9-76a438f2722f'

RADARO_SHORTENER_TOKEN = '900db0a6-9372-4042-b0f1-0401ee845442'

# To prevent unlimited memory growth of celery workers,
# we need to use limited by size batches for orders.
BULK_JOB_CREATION_BATCH_SIZE = 500
BULK_JOB_REPORT_BATCH_SIZE = 500

# Don't set it too high as order_id generated per worker process and collisions may happen
ORDER_SAVE_BATCH_SIZE = 4

RADARO_CSV = {
    'PANDAS_CHUNKSIZE': BULK_JOB_CREATION_BATCH_SIZE
}

CSV_UPLOAD_PREVIEW_AMOUNT = 4

PHONE_SERIALIZER_FIELD = 'radaro_utils.radaro_phone.serializers.RadaroPhoneField'
IMAGEKIT_DEFAULT_CACHEFILE_STRATEGY = 'imagekit.cachefiles.strategies.Optimistic'

CONF_DIR = os.path.join(BASE_DIR, 'conf')
NEWRELIC_INI = os.path.join(CONF_DIR, 'newrelic.ini')

LOCALE_PATHS = [
    os.path.join(CONF_DIR, 'locale'),
]

from merchant.constants import EditableManagerDefaultsMixin as DefaultsMixin

# Distance unit, used as default for merchants
DEFAULT_DISTANCE_SHOW_IN = DefaultsMixin.distance_aliases[DefaultsMixin.KM]

# Date format, used as default for merchants
DEFAULT_DATE_FORMAT = DefaultsMixin.LITTLE_ENDIAN

DELIVER_ADDRESS_2_ENABLED = True

# Maximum interval before deliver_before, within which not_assigned work is considered unallocated
UNALLOCATED_ORDER_INTERVAL = 7  # days

from pillow_heif import register_heif_opener

register_heif_opener()
